-- =====================================================================
-- pgapex metadata repository
--
-- Every application is data: an app owns shared components (navigation,
-- authorization schemes, application items and processes, users) and pages;
-- pages own regions, items, buttons, dynamic actions, validations and
-- processes. The runtime (src/runtime) renders these rows; the builder
-- (src/builder) edits them. Everything here can be scripted with SQL.
-- =====================================================================

create extension if not exists pgcrypto;

create schema meta;

-- Instance-wide secrets. Only the owner (builder/migrations) can read this.
create table meta.instance_setting (
  name  text primary key,
  value text not null
);
insert into meta.instance_setting values ('url_secret', encode(gen_random_bytes(32), 'hex'));

-- ---------------------------------------------------------------------
-- Application and shared components
-- ---------------------------------------------------------------------

create table meta.app (
  id           serial primary key,
  alias        text not null unique check (alias ~ '^[a-z][a-z0-9_-]*$'),
  name         text not null,
  home_page    int  not null default 1,
  -- 'none'      : public app, APP_USER = 'nobody'
  -- 'app_users' : users in meta.app_user, login page at /a/<alias>/login
  authentication text not null default 'app_users' check (authentication in ('none', 'app_users')),
  -- The "parsing schema": all developer SQL runs under SET LOCAL ROLE
  -- <db_role>, so Postgres grants and row level security apply.
  db_role      text,
  -- Show database error details to end users (development only).
  debug        boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Authorization schemes, referenced by name from components. Prefix a
-- reference with '!' to negate it. MUST_NOT_BE_PUBLIC_USER is built in.
create table meta.authz_scheme (
  id            serial primary key,
  app_id        int  not null references meta.app on delete cascade,
  name          text not null check (name ~ '^[A-Z][A-Z0-9_]*$'),
  -- role : the user has the role in meta.app_user.roles (value = role name)
  -- sql  : value is a SQL boolean expression (binds allowed)
  type          text not null check (type in ('role', 'sql')),
  value         text not null,
  error_message text not null default 'You are not authorized to access this page.',
  unique (app_id, name)
);

-- Application items: session state that is not on any page and can only be
-- set by server-side code (application/page processes), never by the browser.
create table meta.app_item (
  id          serial primary key,
  app_id      int  not null references meta.app on delete cascade,
  name        text not null check (name ~ '^[A-Z][A-Z0-9_]*$'),
  description text,
  unique (app_id, name)
);

create table meta.app_process (
  id            serial primary key,
  app_id        int  not null references meta.app on delete cascade,
  seq           int  not null default 10,
  name          text not null,
  -- after_login : once, right after a successful login
  -- before_page : before every page is rendered or submitted
  point         text not null check (point in ('after_login', 'before_page')),
  code          text not null,
  authz         text
);

create table meta.nav_entry (
  id            serial primary key,
  app_id        int  not null references meta.app on delete cascade,
  parent_id     int  references meta.nav_entry on delete cascade,
  seq           int  not null default 10,
  label         text not null,
  icon          text,
  target_page   int,
  authz         text
);

-- ---------------------------------------------------------------------
-- Pages and page components
-- ---------------------------------------------------------------------

create table meta.page (
  id            serial primary key,
  app_id        int  not null references meta.app on delete cascade,
  page_no       int  not null check (page_no > 0),
  name          text not null,
  title         text,
  requires_auth boolean not null default true,
  -- breadcrumb parent
  parent_page   int,
  -- 'modal' pages open in a dialog over the calling page
  mode          text not null default 'normal' check (mode in ('normal', 'modal')),
  -- 'checksum': item values passed in the URL must carry a valid checksum
  -- (generated by the runtime), so users cannot tamper with e.g. ?P3_ID=
  protection    text not null default 'checksum' check (protection in ('unrestricted', 'checksum')),
  authz         text,
  unique (app_id, page_no)
);

create table meta.region (
  id            serial primary key,
  page_id       int  not null references meta.page on delete cascade,
  seq           int  not null default 10,
  title         text,
  -- report : source is a SELECT; interactive table (sort, search, filter, CSV)
  -- form   : items bound to columns of table_name, keyed by pk_column/pk_item
  -- chart  : source is a SELECT returning (label, value)
  -- cards  : source is a SELECT with columns title, subtitle, body, badge, icon
  -- static : source is HTML; &ITEM. placeholders are replaced (escaped)
  type          text not null check (type in ('report', 'form', 'chart', 'cards', 'static')),
  source        text,
  table_name    text,
  pk_column     text,
  pk_item       text,
  -- 12-column grid, like the Universal Theme
  columns       int  not null default 12 check (columns between 1 and 12),
  template      text not null default 'standard' check (template in ('standard', 'plain', 'collapsible')),
  -- SQL boolean expression; the region renders only when true
  condition     text,
  authz         text,
  config        jsonb not null default '{}'
);

create table meta.item (
  id                 serial primary key,
  page_id            int  not null references meta.page on delete cascade,
  region_id          int  references meta.region on delete cascade,
  seq                int  not null default 10,
  -- Items are session-state variables, referenced as :NAME in any SQL.
  -- Convention (as in APEX): P<page>_<NAME>.
  name               text not null check (name ~ '^[A-Z][A-Z0-9_]*$'),
  label              text,
  type               text not null default 'text' check (type in
                       ('text', 'textarea', 'number', 'date', 'datetime', 'select', 'radio',
                        'checkbox', 'switch', 'hidden', 'display', 'password')),
  -- select/radio lists: a SELECT returning (display, return), or
  -- 'STATIC:Display;Return,Other;OTHER'
  lov                text,
  source_column      text,
  default_value      text,
  required           boolean not null default false,
  help               text,
  -- SQL boolean expression; when true the item renders read-only and is
  -- not accepted on submit
  readonly_condition text,
  authz              text,
  -- {"submit_on_change": true, "null_label": "- All -", "cascade_parents": "P3_DEPTNO"}
  config             jsonb not null default '{}',
  unique (page_id, name)
);

create table meta.button (
  id            serial primary key,
  page_id       int  not null references meta.page on delete cascade,
  region_id     int  references meta.region on delete cascade,
  seq           int  not null default 10,
  -- the REQUEST value; processes/validations filter on it
  name          text not null check (name ~ '^[A-Z][A-Z0-9_]*$'),
  label         text not null,
  -- submit   : submits the page with REQUEST = name
  -- redirect : link to target_page (with target_items)
  -- da       : does nothing by itself; a dynamic action handles the click
  action        text not null default 'submit' check (action in ('submit', 'redirect', 'da')),
  target_page   int,
  target_items  jsonb not null default '{}',
  -- SQL boolean expression. Evaluated when rendering AND again on submit,
  -- so a hidden button cannot be "pressed" by a forged request.
  condition     text,
  authz         text,
  hot           boolean not null default false,
  confirm       text
);

create table meta.dynamic_action (
  id                 serial primary key,
  page_id            int  not null references meta.page on delete cascade,
  seq                int  not null default 10,
  name               text not null,
  event              text not null default 'change' check (event in ('change', 'click', 'load')),
  -- item name(s) (comma separated) for change, button name for click
  trigger_element    text,
  -- client-side condition on the triggering item's value
  condition_type     text check (condition_type in ('equals', 'not_equals', 'in_list', 'is_null', 'is_not_null')),
  condition_value    text,
  -- show/hide/enable/disable : client side, reversed when the condition is false
  -- set_value      : code is a SELECT; its columns set affected_items
  -- execute_sql    : run code; returned columns named like items set them
  -- refresh_region : re-render affected_region_id
  -- refresh_item   : re-render affected_items (e.g. dependent lists)
  -- alert / submit : client side
  action             text not null check (action in ('show', 'hide', 'enable', 'disable', 'set_value',
                       'execute_sql', 'refresh_region', 'refresh_item', 'alert', 'submit')),
  affected_items     text,
  affected_region_id int references meta.region on delete set null,
  code               text,
  -- items whose browser values are sent to the server first
  items_to_submit    text,
  message            text,
  authz              text
);

create table meta.validation (
  id           serial primary key,
  page_id      int  not null references meta.page on delete cascade,
  seq          int  not null default 10,
  name         text not null,
  -- item the error is attached to; null = page-level error
  item_name    text,
  -- not_null : item must have a value
  -- sql      : expression is a SQL boolean expression that must be true
  -- regex    : item value must match expression (POSIX, checked in Postgres)
  type         text not null check (type in ('not_null', 'sql', 'regex')),
  expression   text,
  message      text not null,
  when_button  text
);

create table meta.process (
  id              serial primary key,
  page_id         int  not null references meta.page on delete cascade,
  seq             int  not null default 10,
  name            text not null,
  -- form_dml : insert/update/delete the form region's table from its items
  -- sql      : run code (SQL with :BINDS). If it returns a row, columns
  --            named like items (page or application items) set them.
  type            text not null check (type in ('form_dml', 'sql')),
  region_id       int  references meta.region on delete cascade,
  code            text,
  -- 'submit' runs after validations on POST; 'load' runs before rendering
  point           text not null default 'submit' check (point in ('submit', 'load')),
  when_button     text,
  authz           text,
  success_message text
);

-- ---------------------------------------------------------------------
-- Users, sessions, activity
-- ---------------------------------------------------------------------

create table meta.app_user (
  id            serial primary key,
  app_id        int  not null references meta.app on delete cascade,
  username      text not null,
  password_hash text not null,
  roles         text[] not null default '{}',
  active        boolean not null default true,
  last_login_at timestamptz
);
create unique index on meta.app_user (app_id, lower(username));

create table meta.developer (
  username      text primary key,
  password_hash text not null
);

create table meta.session (
  id          uuid primary key default gen_random_uuid(),
  -- sha256 of the cookie token: a leaked table does not leak live sessions
  token_hash  text not null unique,
  app_id      int references meta.app on delete cascade,   -- null = builder session
  username    text,
  csrf_token  text not null default encode(gen_random_bytes(24), 'hex'),
  state       jsonb not null default '{}',
  created_at  timestamptz not null default now(),
  last_seen   timestamptz not null default now()
);
create index on meta.session (last_seen);

create table meta.activity_log (
  id          bigserial primary key,
  at          timestamptz not null default now(),
  app_id      int,
  page_no     int,
  username    text,
  -- page_view, login, login_failed, login_locked, logout, error, forbidden
  event       text not null,
  ip          text,
  elapsed_ms  int,
  detail      text
);
create index on meta.activity_log (app_id, at desc);
create index on meta.activity_log (app_id, lower(username), at) where event = 'login_failed';
create index on meta.activity_log (ip, at) where event = 'login_failed';

create index on meta.region (page_id, seq);
create index on meta.item (page_id, seq);
create index on meta.button (page_id, seq);
create index on meta.dynamic_action (page_id, seq);
create index on meta.validation (page_id, seq);
create index on meta.process (page_id, seq);

-- ---------------------------------------------------------------------
-- Functions available to application SQL (the equivalents of APEX's
-- :APP_USER, v('ITEM'), apex_page.get_url and authorization checks).
-- The runtime sets pgapex.* settings at the start of every transaction.
-- ---------------------------------------------------------------------

create function meta.app_user() returns text
language sql stable as $$
  select coalesce(nullif(current_setting('pgapex.app_user', true), ''), 'nobody')
$$;

create function meta.app_id() returns int
language sql stable as $$
  select nullif(current_setting('pgapex.app_id', true), '')::int
$$;

create function meta.v(p_name text) returns text
language sql stable security definer set search_path = meta, pg_catalog as $$
  select s.state ->> upper(p_name)
    from meta.session s
   where s.id = nullif(current_setting('pgapex.session_id', true), '')::uuid
$$;

-- True when the current application user has the role. Use it in RLS
-- policies: using (owner = meta.app_user() or meta.has_role('admin'))
create function meta.has_role(p_role text) returns boolean
language sql stable security definer set search_path = meta, pg_catalog as $$
  select exists (
    select 1 from meta.app_user u
     where u.app_id = meta.app_id()
       and lower(u.username) = lower(meta.app_user())
       and u.active
       and lower(p_role) = any (select lower(r) from unnest(u.roles) r))
$$;

create function meta.hash_password(p_password text) returns text
language sql volatile as $$ select crypt(p_password, gen_salt('bf', 10)) $$;

create function meta.url_encode(p text) returns text
language sql immutable as $$
  select coalesce(string_agg(
           case when ch ~ '^[A-Za-z0-9_.~-]$' then ch
                else upper(regexp_replace(encode(convert_to(ch, 'UTF8'), 'hex'), '(..)', '%\1', 'g')) end,
           '' order by ord), '')
    from regexp_split_to_table(p, '') with ordinality as t(ch, ord)
$$;

-- Checksum for item values passed in a URL. Must match src/security.ts:
-- hmac_sha256(secret, "<app_id>:<page>:<lower(user)>:<K1>=<v1>&<K2>=<v2>")
create function meta.url_checksum(p_app_id int, p_page int, p_user text, p_items jsonb) returns text
language sql stable security definer set search_path = meta, pg_catalog as $$
  select substr(encode(public.hmac(
           format('%s:%s:%s:%s', p_app_id, p_page, lower(p_user),
             coalesce((select string_agg(upper(key) || '=' || coalesce(value #>> '{}', ''), '&' order by upper(key) collate "C")
                         from jsonb_each(p_items)), '')),
           (select value from meta.instance_setting where name = 'url_secret'), 'sha256'), 'hex'), 1, 32)
$$;
revoke all on function meta.url_checksum(int, int, text, jsonb) from public;

-- Link to a page of the current application, setting items (with checksum),
-- e.g. in a report: select '<a href="' || meta.page_url(3, jsonb_build_object('P3_ID', id)) || '">'
create function meta.page_url(p_page int, p_items jsonb default '{}', p_clear boolean default true) returns text
language sql stable security definer set search_path = meta, pg_catalog as $$
  select format('/a/%s/%s', a.alias, p_page)
      || case when p_items = '{}'::jsonb and not p_clear then '' else '?' end
      || concat_ws('&',
           case when p_clear then 'clear=1' end,
           (select string_agg(upper(key) || '=' || meta.url_encode(coalesce(value #>> '{}', '')), '&' order by upper(key) collate "C")
              from jsonb_each(p_items)),
           case when p_items <> '{}'::jsonb
                then 'cs=' || meta.url_checksum(a.id, p_page, meta.app_user(), p_items) end)
    from meta.app a
   where a.id = meta.app_id()
$$;

-- Verify a password. bcrypt runs even for unknown or inactive users, so the
-- response time does not reveal which usernames exist.
create function meta.authenticate(p_app_id int, p_username text, p_password text) returns text
language plpgsql security definer set search_path = meta, public, pg_catalog as $$
declare
  v_user meta.app_user;
begin
  select * into v_user from meta.app_user
   where app_id = p_app_id and lower(username) = lower(p_username) and active;
  if crypt(coalesce(p_password, ''), coalesce(v_user.password_hash, gen_salt('bf', 10)))
     is distinct from v_user.password_hash then
    return null;
  end if;
  update meta.app_user set last_login_at = now() where id = v_user.id;
  return v_user.username;
end
$$;
revoke all on function meta.authenticate(int, text, text) from public;

grant usage on schema meta to public;
grant execute on function meta.app_user(), meta.app_id(), meta.v(text), meta.has_role(text),
  meta.url_encode(text), meta.page_url(int, jsonb, boolean) to public;
revoke execute on function meta.hash_password(text) from public;

-- ---------------------------------------------------------------------
-- Least-privilege runtime role. The runtime connects as pgapex_runtime:
-- it can read metadata and manage sessions, but cannot read developer
-- accounts or instance secrets. NOINHERIT: it gets an application's
-- data privileges only via SET ROLE <app db_role>.
-- CHANGE THE PASSWORD outside development:
--   alter role pgapex_runtime password '...';
-- ---------------------------------------------------------------------

do $$
begin
  if not exists (select from pg_roles where rolname = 'pgapex_runtime') then
    create role pgapex_runtime login noinherit password 'pgapex_runtime';
  end if;
end
$$;

grant usage on schema meta to pgapex_runtime;
grant select on meta.app, meta.authz_scheme, meta.app_item, meta.app_process, meta.nav_entry,
  meta.page, meta.region, meta.item, meta.button, meta.dynamic_action, meta.validation, meta.process
  to pgapex_runtime;
-- no access to password hashes: logins go through meta.authenticate()
grant select (id, app_id, username, roles, active) on meta.app_user to pgapex_runtime;
grant select, insert, update, delete on meta.session to pgapex_runtime;
grant select, insert on meta.activity_log to pgapex_runtime;
grant usage on sequence meta.activity_log_id_seq to pgapex_runtime;
grant execute on function meta.authenticate(int, text, text) to pgapex_runtime;

-- ---------------------------------------------------------------------
-- Wizard: report page + modal form page for a table (single-column PK).
--   select meta.generate_crud('hr', 'hr.emp', 2, 3);
-- ---------------------------------------------------------------------

create function meta.generate_crud(
  p_app         text,
  p_table       regclass,
  p_report_page int,
  p_form_page   int,
  p_label       text default null,
  p_icon        text default 'table'
) returns void
language plpgsql as $$
declare
  v_app      meta.app;
  v_relname  text;
  v_label    text;
  v_pk       text;
  v_pk_count int;
  v_cols     text;
  v_rpage    int;
  v_fpage    int;
  v_rregion  int;
  v_fregion  int;
  v_pk_item  text;
  v_seq      int := 10;
  v_type     text;
  v_lov      text;
  c          record;
begin
  select * into v_app from meta.app where alias = p_app;
  if v_app.id is null then
    raise exception 'application "%" does not exist', p_app;
  end if;

  select relname into v_relname from pg_class where oid = p_table;
  v_label := coalesce(p_label, initcap(replace(v_relname, '_', ' ')));

  select min(a.attname), count(*) into v_pk, v_pk_count
    from pg_index i
    join pg_attribute a on a.attrelid = i.indrelid and a.attnum = any (i.indkey)
   where i.indrelid = p_table and i.indisprimary;
  if v_pk_count <> 1 then
    raise exception 'table % needs a single-column primary key', p_table;
  end if;
  v_pk_item := format('P%s_%s', p_form_page, upper(v_pk));

  -- report page ------------------------------------------------------
  insert into meta.page (app_id, page_no, name, title, parent_page)
  values (v_app.id, p_report_page, v_label, v_label, nullif(v_app.home_page, p_report_page))
  returning id into v_rpage;

  insert into meta.nav_entry (app_id, seq, label, icon, target_page)
  values (v_app.id, (select coalesce(max(seq), 0) + 10 from meta.nav_entry where app_id = v_app.id and parent_id is null),
          v_label, p_icon, p_report_page);

  select string_agg(quote_ident(attname), ', ' order by attnum) into v_cols
    from pg_attribute
   where attrelid = p_table and attnum > 0 and not attisdropped;

  insert into meta.region (page_id, seq, title, type, source, config)
  values (v_rpage, 10, v_label, 'report',
          format(E'select %s\n  from %s', v_cols, p_table),
          jsonb_build_object('link', jsonb_build_object(
            'column', v_pk, 'page', p_form_page,
            'items', jsonb_build_object(v_pk_item, '#' || v_pk || '#'))))
  returning id into v_rregion;

  insert into meta.button (page_id, region_id, seq, name, label, action, target_page, hot)
  values (v_rpage, v_rregion, 10, 'CREATE', 'Create', 'redirect', p_form_page, true);

  -- form page (modal dialog) -------------------------------------------
  insert into meta.page (app_id, page_no, name, title, parent_page, mode)
  values (v_app.id, p_form_page, v_label || ' Form', v_label, p_report_page, 'modal')
  returning id into v_fpage;

  insert into meta.region (page_id, seq, title, type, table_name, pk_column, pk_item, template)
  values (v_fpage, 10, v_label, 'form', p_table::text, v_pk, v_pk_item, 'plain')
  returning id into v_fregion;

  for c in
    select a.attname, a.attnotnull, t.typcategory, t.typname,
           a.atthasdef or a.attidentity <> '' as hasdef,
           a.attgenerated <> '' as generated,
           fk.confrelid, fk.refcol
      from pg_attribute a
      join pg_type t on t.oid = a.atttypid
      left join lateral (
        select con.confrelid,
               (select attname from pg_attribute
                 where attrelid = con.confrelid and attnum = con.confkey[1]) as refcol
          from pg_constraint con
         where con.conrelid = p_table and con.contype = 'f'
           and array_length(con.conkey, 1) = 1 and con.conkey[1] = a.attnum
         limit 1
      ) fk on true
     where a.attrelid = p_table and a.attnum > 0 and not a.attisdropped
     order by a.attnum
  loop
    continue when c.generated;
    v_lov := null;
    v_type := case
      when c.attname = v_pk        then 'hidden'
      when c.typcategory = 'N'     then 'number'
      when c.typname = 'date'      then 'date'
      when c.typcategory = 'D'     then 'datetime'
      when c.typcategory = 'B'     then 'switch'
      else 'text'
    end;
    if c.confrelid is not null and c.attname <> v_pk then
      -- foreign key: select list showing the first text column of the parent
      v_type := 'select';
      v_lov := format('select %I as d, %I as r from %s order by 1',
        coalesce((select attname from pg_attribute pa join pg_type pt on pt.oid = pa.atttypid
                   where pa.attrelid = c.confrelid and pa.attnum > 0 and not pa.attisdropped
                     and pt.typcategory = 'S' order by pa.attnum limit 1), c.refcol),
        c.refcol, c.confrelid::regclass);
    end if;

    insert into meta.item (page_id, region_id, seq, name, label, type, lov, source_column, required)
    values (v_fpage, v_fregion, v_seq,
            format('P%s_%s', p_form_page, upper(c.attname)),
            initcap(replace(c.attname, '_', ' ')),
            v_type, v_lov, c.attname,
            c.attnotnull and not c.hasdef and c.attname <> v_pk and v_type <> 'switch');
    v_seq := v_seq + 10;
  end loop;

  insert into meta.button (page_id, region_id, seq, name, label, action, target_page, condition, hot, confirm) values
    (v_fpage, v_fregion, 10, 'CANCEL', 'Cancel', 'redirect', p_report_page, null, false, null),
    (v_fpage, v_fregion, 20, 'DELETE', 'Delete', 'submit', p_report_page,
       format(':%s is not null', v_pk_item), false, 'Delete this record?'),
    (v_fpage, v_fregion, 30, 'SAVE', 'Apply Changes', 'submit', p_report_page,
       format(':%s is not null', v_pk_item), true, null),
    (v_fpage, v_fregion, 40, 'CREATE', 'Create', 'submit', p_report_page,
       format(':%s is null', v_pk_item), true, null);

  insert into meta.process (page_id, seq, name, type, region_id)
  values (v_fpage, 10, 'Process form ' || v_label, 'form_dml', v_fregion);
end
$$;

-- ---------------------------------------------------------------------
-- Export / import: an application is portable JSON (commit it to git).
--   select meta.export_app('hr');
--   select meta.import_app(<json>, 'hr_copy');
-- Rows are exported with to_jsonb and imported with jsonb_populate_record,
-- so new columns travel along automatically. Internal ids are kept only
-- as keys to re-link regions and navigation entries.
-- ---------------------------------------------------------------------

create function meta.export_app(p_alias text) returns jsonb
language sql stable as $$
  select jsonb_build_object(
    'format', 'pgapex/2',
    'app', to_jsonb(a) - 'id' - 'created_at' - 'updated_at',
    'authz_schemes', coalesce((select jsonb_agg(to_jsonb(x) - 'id' - 'app_id' order by x.name) from meta.authz_scheme x where x.app_id = a.id), '[]'),
    'app_items', coalesce((select jsonb_agg(to_jsonb(x) - 'id' - 'app_id' order by x.name) from meta.app_item x where x.app_id = a.id), '[]'),
    'app_processes', coalesce((select jsonb_agg(to_jsonb(x) - 'id' - 'app_id' order by x.seq, x.id) from meta.app_process x where x.app_id = a.id), '[]'),
    'nav', coalesce((select jsonb_agg(to_jsonb(x) - 'app_id' order by x.parent_id nulls first, x.seq, x.id) from meta.nav_entry x where x.app_id = a.id), '[]'),
    'pages', coalesce((
      select jsonb_agg(to_jsonb(p) - 'id' - 'app_id' || jsonb_build_object(
        'regions', coalesce((select jsonb_agg(to_jsonb(r) - 'page_id' order by r.seq, r.id) from meta.region r where r.page_id = p.id), '[]'),
        'items', coalesce((select jsonb_agg(to_jsonb(i) - 'id' - 'page_id' order by i.seq, i.id) from meta.item i where i.page_id = p.id), '[]'),
        'buttons', coalesce((select jsonb_agg(to_jsonb(b) - 'id' - 'page_id' order by b.seq, b.id) from meta.button b where b.page_id = p.id), '[]'),
        'dynamic_actions', coalesce((select jsonb_agg(to_jsonb(d) - 'id' - 'page_id' order by d.seq, d.id) from meta.dynamic_action d where d.page_id = p.id), '[]'),
        'validations', coalesce((select jsonb_agg(to_jsonb(v) - 'id' - 'page_id' order by v.seq, v.id) from meta.validation v where v.page_id = p.id), '[]'),
        'processes', coalesce((select jsonb_agg(to_jsonb(x) - 'id' - 'page_id' order by x.seq, x.id) from meta.process x where x.page_id = p.id), '[]')
      ) order by p.page_no)
      from meta.page p where p.app_id = a.id), '[]'))
  from meta.app a
  where a.alias = p_alias
$$;

create function meta.import_app(p_doc jsonb, p_alias text default null) returns int
language plpgsql as $$
declare
  v_app_id  int;
  v_page_id int;
  v_page    jsonb;
  v_e       jsonb;
  v_rmap    jsonb;
  v_nmap    jsonb := '{}';
  v_new_id  int;
begin
  if p_doc->>'format' is distinct from 'pgapex/2' then
    raise exception 'unsupported export format %', p_doc->>'format';
  end if;

  insert into meta.app
  select (jsonb_populate_record(null::meta.app, p_doc->'app' || jsonb_build_object(
            'id', nextval('meta.app_id_seq'),
            'alias', coalesce(p_alias, p_doc->'app'->>'alias'),
            'created_at', now(), 'updated_at', now()))).*
  returning id into v_app_id;

  insert into meta.authz_scheme
  select (jsonb_populate_record(null::meta.authz_scheme, e || jsonb_build_object('id', nextval('meta.authz_scheme_id_seq'), 'app_id', v_app_id))).*
    from jsonb_array_elements(p_doc->'authz_schemes') e;
  insert into meta.app_item
  select (jsonb_populate_record(null::meta.app_item, e || jsonb_build_object('id', nextval('meta.app_item_id_seq'), 'app_id', v_app_id))).*
    from jsonb_array_elements(p_doc->'app_items') e;
  insert into meta.app_process
  select (jsonb_populate_record(null::meta.app_process, e || jsonb_build_object('id', nextval('meta.app_process_id_seq'), 'app_id', v_app_id))).*
    from jsonb_array_elements(p_doc->'app_processes') e;

  -- navigation: parents are exported first, so their new ids are known
  for v_e in select * from jsonb_array_elements(p_doc->'nav') loop
    insert into meta.nav_entry
    select (jsonb_populate_record(null::meta.nav_entry, v_e || jsonb_build_object(
              'id', nextval('meta.nav_entry_id_seq'), 'app_id', v_app_id,
              'parent_id', v_nmap->>(v_e->>'parent_id')))).*
    returning id into v_new_id;
    v_nmap := v_nmap || jsonb_build_object(v_e->>'id', v_new_id);
  end loop;

  for v_page in select * from jsonb_array_elements(p_doc->'pages') loop
    insert into meta.page
    select (jsonb_populate_record(null::meta.page, v_page || jsonb_build_object('id', nextval('meta.page_id_seq'), 'app_id', v_app_id))).*
    returning id into v_page_id;

    v_rmap := '{}';
    for v_e in select * from jsonb_array_elements(v_page->'regions') loop
      insert into meta.region
      select (jsonb_populate_record(null::meta.region, v_e || jsonb_build_object('id', nextval('meta.region_id_seq'), 'page_id', v_page_id))).*
      returning id into v_new_id;
      v_rmap := v_rmap || jsonb_build_object(v_e->>'id', v_new_id);
    end loop;

    insert into meta.item
    select (jsonb_populate_record(null::meta.item, e || jsonb_build_object('id', nextval('meta.item_id_seq'), 'page_id', v_page_id, 'region_id', v_rmap->>(e->>'region_id')))).*
      from jsonb_array_elements(v_page->'items') e;
    insert into meta.button
    select (jsonb_populate_record(null::meta.button, e || jsonb_build_object('id', nextval('meta.button_id_seq'), 'page_id', v_page_id, 'region_id', v_rmap->>(e->>'region_id')))).*
      from jsonb_array_elements(v_page->'buttons') e;
    insert into meta.dynamic_action
    select (jsonb_populate_record(null::meta.dynamic_action, e || jsonb_build_object('id', nextval('meta.dynamic_action_id_seq'), 'page_id', v_page_id, 'affected_region_id', v_rmap->>(e->>'affected_region_id')))).*
      from jsonb_array_elements(v_page->'dynamic_actions') e;
    insert into meta.validation
    select (jsonb_populate_record(null::meta.validation, e || jsonb_build_object('id', nextval('meta.validation_id_seq'), 'page_id', v_page_id))).*
      from jsonb_array_elements(v_page->'validations') e;
    insert into meta.process
    select (jsonb_populate_record(null::meta.process, e || jsonb_build_object('id', nextval('meta.process_id_seq'), 'page_id', v_page_id, 'region_id', v_rmap->>(e->>'region_id')))).*
      from jsonb_array_elements(v_page->'processes') e;
  end loop;

  return v_app_id;
end
$$;

-- Default developer account for the builder. CHANGE THIS.
insert into meta.developer (username, password_hash)
values ('admin', meta.hash_password('admin'));
