// Sprint 36 item 4: blueprints (spec-driven development) — checks, SQL, the
// builder's editor, AI draft (scripted mock: no real API calls), review and
// creation in one transaction.
import { after, before, describe, test } from 'node:test';
import assert from 'node:assert/strict';
import type { FastifyInstance } from 'fastify';
import '../src/env.ts';

process.env.PGAPEX_SECRET_KEY = 'test-only-secret-key-0123456789abcdef';

const { buildApp } = await import('../src/app.ts');
const { closePools, owner, runtime } = await import('../src/db.ts');
const { encryptSecret } = await import('../src/secrets.ts');
const { blueprintSql, checkBlueprint, fromDraft, tableOrder } = await import('../src/blueprint.ts');
const { EXAMPLE } = await import('../src/builder/blueprints.ts');
const { Browser } = await import('./helpers.ts');
const { startScriptMock } = await import('./ai-script-mock.ts');

let app: FastifyInstance;
let mock: Awaited<ReturnType<typeof startScriptMock>>;
let admin: InstanceType<typeof Browser>;
const SVC = 'T_AI4_BLUEPRINT';
const ALIAS = 'bp-s36';
const SCHEMA = 'bp_s36';
const spec = (over: Record<string, unknown> = {}) => JSON.stringify({ ...EXAMPLE, alias: ALIAS, schema: SCHEMA, ...over });
const sigOf = (body: string) => /name="sig" value="([^"]+)"/.exec(body)?.[1] ?? '';
const unescape = (s: string) => s.replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');

async function cleanup() {
  await owner.query(`delete from meta.app where alias like 'bp-s36%'`);
  await owner.query(`delete from meta.blueprint where name like 'T_BP%' or created_by = 'admin' and spec->>'alias' like 'bp-s36%'`);
  await owner.query(`delete from meta.account where username = 'bp_s36_admin'`);
  await owner.query(`drop schema if exists ${SCHEMA} cascade`);
  await owner.query(`drop schema if exists bp_s36_ai cascade`);
  for (const r of ['app_bp_s36', 'app_bp_s36_ai']) {
    if ((await owner.query('select 1 from pg_roles where rolname = $1', [r])).rowCount) {
      await owner.query(`revoke ${r} from pgapex_runtime`).catch(() => {});
      await owner.query(`drop owned by ${r}`).catch(() => {});
      await owner.query(`drop role ${r}`);
    }
  }
}

before(async () => {
  mock = await startScriptMock();
  app = await buildApp({ logger: false });
  await cleanup();
  await owner.query(`delete from meta.ai_service where name = $1`, [SVC]);
  const id = (await owner.one(`insert into meta.ai_service (name, provider, model, base_url, api_key_enc) values ($1, 'anthropic', 'claude-opus-5-5', $2, $3) returning id`,
    [SVC, `${mock.base}/claude`, encryptSecret('sk-ant-bp')])).id;
  await owner.query('update meta.builder_ai set service_id = $1', [id]);
  admin = new Browser(app);
  await admin.get('/builder/login');
  await admin.post('/builder/login', { __csrf: admin.lastCsrf, username: 'admin', password: 'admin' });
  await admin.get('/builder');
});

after(async () => {
  await cleanup();
  await owner.query('update meta.builder_ai set service_id = null');
  await owner.query(`delete from meta.ai_service where name = $1`, [SVC]);
  await mock.close();
  await app.close();
  await closePools();
});

describe('blueprint checks and SQL', () => {
  test('the example is valid; its SQL quotes names and values', () => {
    const { blueprint, problems } = checkBlueprint(JSON.parse(spec()));
    assert.deepEqual(problems, []);
    assert.equal(blueprint!.pages.length, 3);
    const sql = blueprintSql({ ...blueprint!, tables: [{ name: 'note', label: null, columns: [{ name: 'kind', type: 'text', required: false, unique: false, values: ["it's", 'b'], references: null }] }] });
    assert.equal(sql[0], `create table "bp_s36"."note" (\n  id bigint generated by default as identity primary key,\n  "kind" text check ("kind" in ('it''s', 'b'))\n)`);
  });

  test('problems: names, id columns, references, types, pages, sample rows', () => {
    const bad = checkBlueprint({
      name: 'X', alias: 'Bad Alias', schema: 'meta',
      tables: [
        { name: 'a', columns: [{ name: 'id' }, { name: 'b_id', references: 'nope' }, { name: 'n', type: 'number', values: ['x'] }, { name: 'q', type: 'money' }] },
        { name: 'A b', columns: [{ name: 'x' }] },
      ],
      pages: [{ type: 'report_form', table: 'a', page: 2, form_page: 2 }, { type: 'shell', page: 3 }, { type: 'grid', table: 'zzz', page: 1 }],
      sample_data: [{ table: 'a', columns: ['n', 'nope'], rows: [[1]] }],
    });
    assert.equal(bad.blueprint, null);
    const all = bad.problems.join('\n');
    for (const re of [/"alias"/, /"schema": meta/, /not "id"/, /"references" names a table/, /"values" is for text columns/, /"type" is one of/, /table "A b": "name"/,
      /page 2 is used twice/, /"type" is one of report_form/, /page numbers are 2 to 99999/, /"table" names a table/, /"columns" are columns of a/, /each row is a list of 2 values/])
      assert.match(all, re);
  });

  test('referenced tables come first; a cycle of required references is refused', () => {
    const t = (name: string, ref: string | null, required = true) => ({ name, label: null, columns: [{ name: 'r', type: 'integer' as const, required, unique: false, values: [], references: ref }] });
    assert.deepEqual(tableOrder([t('child', 'parent'), t('parent', null)])!.map((x) => x.name), ['parent', 'child']);
    assert.equal(tableOrder([t('a', 'b'), t('b', 'a')]), null);
    assert.deepEqual(tableOrder([t('a', 'b', false), t('b', 'a')])!.map((x) => x.name), ['a', 'b']);
    assert.match(checkBlueprint({ name: 'X', alias: 'x', tables: [{ name: 'a', columns: [{ name: 'b_id', references: 'b', required: true }] }, { name: 'b', columns: [{ name: 'a_id', references: 'a', required: true }] }] }).problems.join(), /cycle/);
  });

  test('without pages each table gets a report and form', () => {
    const { blueprint } = checkBlueprint({ name: 'X', alias: 'x', tables: [{ name: 'a', columns: [{ name: 'n' }] }, { name: 'b', columns: [{ name: 'n' }] }] });
    assert.deepEqual(blueprint!.pages.map((p) => [p.type, p.table, p.page, p.form_page, p.label]), [['report_form', 'a', 2, 3, 'A'], ['report_form', 'b', 4, 5, 'B']]);
  });
});

describe('blueprints in the builder', () => {
  test('review, then create: tables, rows, pages, menu, the role\'s grants; the blueprint remembers the application', async () => {
    assert.match((await admin.get('/builder/create')).body, /From a blueprint/);
    const editor = (await admin.get('/builder/blueprints/new')).body;
    assert.match(editor, /&quot;blueprint&quot;: 1/);
    // creating without the review is refused
    assert.equal((await admin.submit('/builder/blueprints/create', { name: 'T_BP one', spec: spec(), sig: 'x', admin_user: 'bp_s36_admin', admin_password: 'Bp-s36-password!' })).statusCode, 403);
    const review = await admin.submit('/builder/blueprints/review', { name: 'T_BP one', spec: spec() });
    assert.equal(review.statusCode, 200);
    assert.match(review.body, /Review: Projects/);
    assert.match(review.body, /create table &quot;bp_s36&quot;\.&quot;project&quot;/);
    assert.match(review.body, /alter table &quot;bp_s36&quot;\.&quot;task&quot; add foreign key \(&quot;project_id&quot;\) references &quot;bp_s36&quot;\.&quot;project&quot; \(id\)/);
    assert.match(review.body, /Page 2 and 3: Projects/);
    const sig = sigOf(review.body);
    assert.ok(sig);
    // a changed blueprint needs its own review
    assert.equal((await admin.submit('/builder/blueprints/create', { name: 'T_BP one', spec: spec({ name: 'Other' }), sig, admin_user: 'bp_s36_admin', admin_password: 'Bp-s36-password!' })).statusCode, 403);
    const created = await admin.submit('/builder/blueprints/create', { name: 'T_BP one', spec: unescape(/name="spec" value="([^"]*)"/.exec(review.body)![1]), sig, admin_user: 'bp_s36_admin', admin_password: 'Bp-s36-password!' });
    assert.equal(created.statusCode, 303, /No application was created: ([^<]*)/.exec(created.body)?.[1] ?? '');
    const a = await owner.one('select id, name, db_role, authentication from meta.app where alias = $1', [ALIAS]);
    assert.deepEqual({ name: a.name, role: a.db_role, auth: a.authentication }, { name: 'Projects', role: 'app_bp_s36', auth: 'app_users' });
    assert.deepEqual((await owner.query(`select page_no from meta.page where app_id = $1 order by 1`, [a.id])).rows.map((r) => r.page_no), [1, 2, 3, 4, 5, 6, 7]);
    assert.deepEqual((await owner.query(`select name, status from bp_s36.project order by id`)).rows, [{ name: 'Website', status: 'Active' }, { name: 'Office move', status: 'Planned' }]);
    assert.equal((await owner.one(`select count(*)::int as n from bp_s36.task where project_id = 1`)).n, 2);
    await owner.query(`insert into bp_s36.project (name, status) values ('Third', 'Done')`);
    assert.equal((await owner.one(`select max(id)::int as n from bp_s36.project`)).n, 3, 'the identity continues after the sample ids');
    await assert.rejects(owner.query(`insert into bp_s36.project (name, status) values ('Fourth', 'Unknown')`), /check/);
    await assert.rejects(owner.query(`insert into bp_s36.task (project_id, title) values (99, 'x')`), /foreign key/);
    assert.equal((await owner.one(`select has_table_privilege('app_bp_s36', 'bp_s36.task', 'insert') as ok`)).ok, true);
    assert.equal((await owner.one(`select app_id from meta.blueprint where name = 'T_BP one'`)).app_id, a.id);
    const b = new Browser(app);
    await b.login('bp_s36_admin', 'Bp-s36-password!', ALIAS);
    const run = await b.get(`/a/${ALIAS}/2`);
    assert.equal(run.statusCode, 200);
    assert.match(run.body, /Website/);
    assert.match((await b.get(`/a/${ALIAS}/7`)).body, /chart/i, 'the dashboard');
  });

  test('a blueprint whose alias exists, or with problems, shows the problems and no create button', async () => {
    const again = await admin.submit('/builder/blueprints/review', { name: 'T_BP two', spec: spec() });
    assert.match(again.body, /An application with the alias bp-s36 already exists/);
    assert.doesNotMatch(again.body, /name="sig"/);
    assert.match((await admin.submit('/builder/blueprints/review', { name: 'T_BP two', spec: '{nope' })).body, /Not valid JSON/);
  });

  test('a failing build creates nothing (one transaction)', async () => {
    const s = spec({ alias: 'bp-s36-fail', schema: 'bp_s36_fail', sample_data: [{ table: 'task', columns: ['project_id', 'title'], rows: [[42, 'Orphan']] }] });
    const review = await admin.submit('/builder/blueprints/review', { name: 'T_BP fail', spec: s });
    const res = await admin.submit('/builder/blueprints/create', { name: 'T_BP fail', spec: s, sig: sigOf(review.body), admin_user: 'bp_s36_admin', admin_password: 'Bp-s36-password!' });
    assert.match(res.body, /No application was created/);
    assert.equal((await owner.one(`select count(*)::int as n from meta.app where alias = 'bp-s36-fail'`)).n, 0);
    assert.equal((await owner.one(`select to_regnamespace('bp_s36_fail') is null as gone`)).gone, true);
  });

  test('an AI draft fills the editor; nothing is created or saved', async () => {
    mock.script = [{ text: JSON.stringify({
      name: 'Hours', alias: 'bp-s36-ai', schema: 'bp_s36_ai',
      tables: [{ name: 'person', label: 'People', columns: [{ name: 'name', type: 'text', required: true, unique: false, values: [], references: '' }] },
        { name: 'entry', label: 'Hours', columns: [{ name: 'person_id', type: 'integer', required: true, unique: false, values: [], references: 'person' }, { name: 'hours', type: 'number', required: false, unique: false, values: [], references: '' }] }],
      pages: [{ type: 'report_form', table: 'entry', page: 2, form_page: 3, label: 'Hours', text: '' }, { type: 'blank', table: '', page: 4, form_page: null, label: 'Help', text: 'How to <b>log</b> hours.' }],
      dashboard: false, sample_data: [{ table: 'person', columns: ['id', 'name'], rows: [[1, 'Ann']] }],
    }) }];
    const before = (await owner.one('select count(*)::int as n from meta.blueprint')).n;
    const res = await admin.submit('/builder/blueprints/draft', { name: 'Blueprint', description: 'Log hours per person' });
    assert.match(res.body, /Drafted by AI/);
    const text = unescape(/<textarea id="f_spec"[^>]*>([\s\S]*?)<\/textarea>/.exec(res.body)![1]);
    const drafted = JSON.parse(text);
    assert.deepEqual(drafted.tables[1].columns[0], { name: 'person_id', references: 'person', required: true });
    assert.equal(drafted.pages[1].text, 'How to <b>log</b> hours.');
    assert.deepEqual(checkBlueprint(drafted).problems, []);
    const r = mock.seen.at(-1)!;
    assert.equal(r.body.messages[0].content, 'Log hours per person');
    assert.equal(r.body.output_config.format.schema.additionalProperties, false);
    assert.equal((await owner.one('select count(*)::int as n from meta.blueprint')).n, before);
    assert.equal((await owner.one(`select count(*)::int as n from meta.app where alias = 'bp-s36-ai'`)).n, 0);
    // a blank page's text is escaped when created
    const review = await admin.submit('/builder/blueprints/review', { name: 'T_BP ai', spec: text });
    await admin.submit('/builder/blueprints/create', { name: 'T_BP ai', spec: text, sig: sigOf(review.body), admin_user: 'bp_s36_admin', admin_password: 'Bp-s36-password!' });
    const help = await owner.one(`select r.source from meta.region r join meta.page p on p.id = r.page_id join meta.app a on a.id = p.app_id where a.alias = 'bp-s36-ai' and p.page_no = 4`);
    assert.equal(help.source, '<p>How to &lt;b&gt;log&lt;/b&gt; hours.</p>');
    assert.deepEqual(fromDraft({ name: 'x', tables: [], pages: [], dashboard: false, sample_data: [] }), { blueprint: 1, name: 'x', alias: undefined, schema: undefined, authentication: 'app_users', tables: [], pages: [] });
  });

  test('save, open and delete a blueprint', async () => {
    const res = await admin.submit('/builder/blueprints/save', { name: 'T_BP saved', spec: spec({ alias: 'bp-s36-saved' }) });
    assert.equal(res.statusCode, 303);
    const id = (await owner.one(`select id from meta.blueprint where name = 'T_BP saved'`)).id;
    assert.match((await admin.get('/builder/blueprints')).body, /T_BP saved/);
    assert.match((await admin.get(`/builder/blueprints/${id}`)).body, /bp-s36-saved/);
    assert.match((await admin.submit('/builder/blueprints/save', { name: 'T_BP bad', spec: '[1]' })).body, /A blueprint is a JSON object/);
    await admin.submit(`/builder/blueprints/${id}/delete`, {});
    assert.equal((await owner.one(`select count(*)::int as n from meta.blueprint where id = $1`, [id])).n, 0);
    await assert.rejects(runtime.query('select * from meta.blueprint'), /permission denied/);
  });
});
