// Sprint 32 item 4: create page wizards for cards, calendar, chart, map,
// faceted search, form only and master-detail pages (migration 047,
// src/builder/wizards.ts). A small app of its own with a few tables.
import { after, before, describe, test } from 'node:test';
import assert from 'node:assert/strict';
import type { FastifyInstance } from 'fastify';
import '../src/env.ts';
import { buildApp } from '../src/app.ts';
import { closePools, owner } from '../src/db.ts';
import { wizardOptions } from '../src/builder/wizards.ts';
import { Browser, formFields } from './helpers.ts';

let app: FastifyInstance;
let appId: number;
const alias = 'wizards-s32';
const ROLE = 'pgkiln_s32_wizards';
const SCHEMA = 'wiz32';

before(async () => {
  app = await buildApp({ logger: false });
  await owner.query(`delete from meta.app where alias = $1`, [alias]);
  await owner.query(`drop schema if exists ${SCHEMA} cascade`);
  await owner.query(`drop owned by ${ROLE}`).catch(() => undefined);
  await owner.query(`drop role if exists ${ROLE}`);
  await owner.query(`create role ${ROLE} nologin`);
  await owner.query(`grant ${ROLE} to pgkiln_runtime`);
  await owner.query(`create schema ${SCHEMA}`);
  await owner.query(`
    create table ${SCHEMA}.category (id int generated by default as identity primary key, name text not null unique);
    create table ${SCHEMA}.product (
      id int generated by default as identity primary key, name text not null, category_id int references ${SCHEMA}.category,
      price numeric(9,2), in_stock boolean not null default true, released date, notes text, picture bytea);
    create table ${SCHEMA}.meeting (id serial primary key, subject text not null, starts_at timestamp not null, ends_at timestamp, room text);
    create table ${SCHEMA}.site (id serial primary key, name text not null, latitude numeric(8,5), longitude numeric(8,5), spot point, location text);
    create domain ${SCHEMA}.geometry as text;
    create table ${SCHEMA}.parcel (id serial primary key, label text, shape ${SCHEMA}.geometry);
    create table ${SCHEMA}.nokey (a text, b int);
    create view ${SCHEMA}.product_v as select p.name, c.name as category, p.price from ${SCHEMA}.product p left join ${SCHEMA}.category c on c.id = p.category_id;
    insert into ${SCHEMA}.category (name) values ('Tools'), ('Toys');
    insert into ${SCHEMA}.product (name, category_id, price, released) values
      ('Hammer', 1, 12.50, '2026-01-10'), ('Saw', 1, 20, '2026-02-01'), ('Kite', 2, 8, '2026-03-15');
    insert into ${SCHEMA}.meeting (subject, starts_at, ends_at, room) values ('Kick-off', date_trunc('month', now()) + interval '3 days 9 hours', date_trunc('month', now()) + interval '3 days 10 hours', 'A');
    insert into ${SCHEMA}.site (name, latitude, longitude, spot, location) values ('Head office', 52.37, 4.89, point(4.89, 52.37), '52.37,4.89');
    grant usage on schema ${SCHEMA} to ${ROLE};
    grant select, insert, update, delete on all tables in schema ${SCHEMA} to ${ROLE};
    grant usage on all sequences in schema ${SCHEMA} to ${ROLE};
  `);
  appId = (await owner.one(`insert into meta.app (alias, name, authentication, db_role) values ($1, 'Wizards', 'none', $2) returning id`, [alias, ROLE])).id;
  await owner.query(`insert into meta.page (app_id, page_no, name, requires_auth) values ($1, 1, 'Home', false)`, [appId]);
  await owner.query(`update meta.app set home_page = 1 where id = $1`, [appId]);
});

after(async () => {
  await owner.query('delete from meta.app where id = $1', [appId]);
  await owner.query(`drop schema if exists ${SCHEMA} cascade`);
  await owner.query(`drop owned by ${ROLE}`);
  await owner.query(`drop role if exists ${ROLE}`);
  await app.close();
  await closePools();
});

const builder = async () => {
  const b = new Browser(app);
  await b.get('/builder/login');
  assert.equal((await b.submit('/builder/login', { username: 'admin', password: 'admin' })).statusCode, 303);
  return b;
};
const defaults = async (kind: string, table: string) => (await owner.one('select meta.wizard_defaults($1, $2::regclass) as d', [kind, table])).d;
const generate = (kind: string, table: string, page: number, options: Record<string, unknown> = {}) =>
  owner.one('select meta.generate_page($1, $2, $3::regclass, $4, $5::jsonb) as id', [alias, kind, table, page, JSON.stringify(options)]);
const regions = async (page: number) =>
  (await owner.query(`select r.* from meta.region r join meta.page p on p.id = r.page_id where p.app_id = $1 and p.page_no = $2 order by r.seq`, [appId, page])).rows;
const publish = () => owner.query('update meta.page set requires_auth = false where app_id = $1', [appId]);
const visitor = () => new Browser(app);

describe('defaults from the catalog', () => {
  test('columns, keys, dates, positions and foreign keys', async () => {
    const cards = await defaults('cards', `${SCHEMA}.product`);
    assert.equal(cards.title, 'name');
    assert.equal(cards.subtitle, 'category_id', 'a foreign key is the subtitle');
    assert.equal(cards.icon, 'layers');
    const cal = await defaults('calendar', `${SCHEMA}.meeting`);
    assert.deepEqual([cal.start, cal.end, cal.title, cal.drag], ['starts_at', 'ends_at', 'subject', false]);
    const chart = await defaults('chart', `${SCHEMA}.product`);
    assert.deepEqual([chart.label_column, chart.function, chart.chart], ['category_id', 'count', 'bar']);
    const map = await defaults('map', `${SCHEMA}.site`);
    assert.equal(map.location, 'spot', 'a point wins over coordinates and text');
    assert.equal((await defaults('map', `${SCHEMA}.parcel`)).location, 'shape', 'a geometry column');
    const facets = await defaults('facets', `${SCHEMA}.product`);
    assert.deepEqual(facets.facets, ['category_id', 'in_stock', 'released', 'price']);
    assert.ok(!facets.columns.includes('picture'), 'no binary columns in the report');
    const md = await defaults('master_detail', `${SCHEMA}.category`);
    assert.deepEqual([md.detail, md.detail_column, md.label], [`${SCHEMA}.product`, 'category_id', 'Category and Product']);
    const form = await defaults('form', `${SCHEMA}.product`);
    assert.equal(form.nav, false);
    assert.ok(!form.columns.includes('picture'));
    await assert.rejects(defaults('nonsense', `${SCHEMA}.product`), /unknown page type/);
  });
});

describe('generate_page', () => {
  test('cards with a form page: the cards link to the form, Create opens it, the form saves', async () => {
    await generate('cards', `${SCHEMA}.product`, 10, { form_page: 11 });
    const [r] = await regions(10);
    assert.equal(r.type, 'cards');
    assert.match(r.source, /\(select p\.name from wiz32\.category p where p\.id = t\.category_id\) as subtitle/);
    assert.deepEqual(r.config.link, { page: 11, items: { P11_ID: '#id#' } });
    const form = await regions(11);
    assert.equal(form[0].type, 'form');
    const nav = (await owner.query('select label, target_page from meta.nav_entry where app_id = $1', [appId])).rows;
    assert.deepEqual(nav, [{ label: 'Product', target_page: 10 }]);
    await publish();
    const v = visitor();
    const page = (await v.get(`/a/${alias}/10`)).body;
    assert.match(page, /Hammer/);
    assert.match(page, /Tools/);
    assert.match(page, /href="\/a\/wizards-s32\/11\?P11_ID=1&amp;cs=/);
    // the generated modal form creates a row
    const f = (await v.get(`/a/${alias}/11`)).body;
    assert.match(f, /name="P11_CATEGORY_ID"/);
    assert.doesNotMatch(f, /P11_PICTURE/, 'no binary columns in the form');
    const res = await v.post(`/a/${alias}/11`, { ...formFields(f), P11_NAME: 'Drill', P11_CATEGORY_ID: '1', P11_PRICE: '99', __request: 'CREATE' });
    assert.ok([200, 303].includes(res.statusCode), res.body.slice(0, 300));
    assert.equal((await owner.one(`select count(*)::int as n from ${SCHEMA}.product where name = 'Drill' and price = 99`)).n, 1);
  });

  test('calendar with create, link and drag and drop', async () => {
    await generate('calendar', `${SCHEMA}.meeting`, 12, { form_page: 13, drag: true });
    const [r] = await regions(12);
    assert.equal(r.type, 'calendar');
    assert.match(r.source, /t\.starts_at as start_date,\s+t\.ends_at as end_date,\s+t\.subject as title,\s+t\.id/);
    assert.deepEqual(r.config.create, { page: 13, items: { P13_STARTS_AT: '#start#', P13_ENDS_AT: '#end#' } });
    assert.equal(r.config.move, 'update wiz32.meeting set starts_at = :NEW_START::timestamp without time zone, ends_at = :NEW_END::timestamp without time zone where id = :EVENT_ID::integer');
    await publish();
    const page = (await visitor().get(`/a/${alias}/12`)).body;
    assert.match(page, /Kick-off/);
    assert.match(page, /draggable="true"/);
  });

  test('chart: count per foreign key value, sum per column; checks the function and type', async () => {
    await generate('chart', `${SCHEMA}.product`, 14);
    let [r] = await regions(14);
    assert.match(r.source, /count\(\*\) as "Count"/);
    await generate('chart', `${SCHEMA}.product`, 15, { chart: 'column', function: 'sum', value_column: 'price', label_column: 'in_stock' });
    [r] = await regions(15);
    assert.match(r.source, /sum\(t\.price\) as "Sum of Price"/);
    assert.equal(r.config.kind, 'column');
    await publish();
    const page = (await visitor().get(`/a/${alias}/14`)).body;
    assert.match(page, /Tools/);
    assert.match(page, /chart/);
    await assert.rejects(generate('chart', `${SCHEMA}.product`, 16, { function: 'sum' }), /needs a number column/);
    await assert.rejects(generate('chart', `${SCHEMA}.product`, 16, { function: 'pg_sleep' }), /unknown function/);
    await assert.rejects(generate('chart', `${SCHEMA}.product`, 16, { chart: 'gauge' }), /unknown chart type/);
  });

  test('map: a point, coordinates or text, with a list filtered by the map area', async () => {
    await generate('map', `${SCHEMA}.site`, 16);
    let rs = await regions(16);
    assert.deepEqual(rs.map((r) => r.type), ['map', 'report']);
    assert.match(rs[0].source, /t\.spot\[1\] as lat, t\.spot\[0\] as lng/);
    assert.equal(rs[0].config.report, rs[1].id);
    await generate('map', `${SCHEMA}.site`, 17, { location: null, report: false });
    rs = await regions(17);
    assert.deepEqual(rs.map((r) => r.type), ['map']);
    assert.match(rs[0].source, /t\.latitude as lat, t\.longitude as lng/);
    await generate('map', `${SCHEMA}.parcel`, 18);
    assert.match((await regions(18))[0].source, /st_asgeojson\(t\.shape::geometry\)/);
    await publish();
    const page = (await visitor().get(`/a/${alias}/16`)).body;
    assert.match(page, /Head office/);
    await assert.rejects(generate('map', `${SCHEMA}.nokey`, 19), /a map needs latitude and longitude/);
  });

  test('faceted search: a report with foreign key names, facets of the right kind', async () => {
    await generate('facets', `${SCHEMA}.product`, 20, { form_page: 21 });
    const rs = await regions(20);
    assert.deepEqual(rs.map((r) => r.type), ['facets', 'report']);
    assert.equal(rs[0].config.report, rs[1].id);
    assert.deepEqual(rs[0].config.facets, [
      { column: 'category_id_name', label: 'Category' },
      { column: 'in_stock', label: 'In Stock' },
      { column: 'released', label: 'Released', type: 'range', custom: true },
      { column: 'price', label: 'Price', type: 'range', custom: true },
    ]);
    assert.match(rs[1].source, /as category_id_name/);
    await publish();
    const v = visitor();
    const page = (await v.get(`/a/${alias}/20`)).body;
    assert.match(page, /Toys/);
    // a facet filters the report (no JavaScript: a GET form)
    const filtered = (await v.get(`/a/${alias}/20?r${rs[1].id}_x_category_id_name=Toys`)).body;
    const table = filtered.slice(filtered.indexOf(`id="R${rs[1].id}"`));
    assert.match(table, /Kite/);
    assert.doesNotMatch(table, /Hammer/);
  });

  test('form only: a normal page that returns to a page of choice', async () => {
    await generate('form', `${SCHEMA}.meeting`, 22, { return_page: 12, columns: ['subject'] });
    const p = await owner.one('select mode, parent_page from meta.page where app_id = $1 and page_no = 22', [appId]);
    assert.deepEqual(p, { mode: 'normal', parent_page: 12 });
    const items = (await owner.query(`select i.name from meta.item i join meta.page p on p.id = i.page_id where p.app_id = $1 and p.page_no = 22 order by i.seq`, [appId])).rows.map((r) => r.name);
    assert.deepEqual(items, ['P22_ID', 'P22_SUBJECT', 'P22_STARTS_AT'], 'required columns are always included');
    const buttons = (await owner.query(`select b.name, b.target_page from meta.button b join meta.page p on p.id = b.page_id where p.app_id = $1 and p.page_no = 22 order by b.seq`, [appId])).rows;
    assert.ok(buttons.every((b) => b.target_page === 12));
    assert.equal((await owner.one(`select count(*)::int as n from meta.nav_entry where app_id = $1 and target_page = 22`, [appId])).n, 0, 'no menu entry by default');
  });

  test('master-detail: two grids, the detail follows the selection', async () => {
    await generate('master_detail', `${SCHEMA}.category`, 23);
    const rs = await regions(23);
    assert.deepEqual(rs.map((r) => r.type), ['grid', 'grid']);
    assert.deepEqual(rs[0].config.select_row, { column: 'id', item: 'P23_ID' });
    assert.deepEqual(rs[1].config.master, { item: 'P23_ID', column: 'category_id' });
    assert.match(rs[1].source, /where category_id = :P23_ID::integer/);
    assert.doesNotMatch(rs[1].source, /picture/);
    const procs = (await owner.query(`select x.type from meta.process x join meta.page p on p.id = x.page_id where p.app_id = $1 and p.page_no = 23`, [appId])).rows;
    assert.deepEqual(procs.map((x) => x.type), ['grid_dml', 'grid_dml']);
    await publish();
    const page = (await visitor().get(`/a/${alias}/23`)).body;
    assert.match(page, /Tools/);
    assert.match(page, /grid-pick-link/);
  });

  test('refusals: existing pages, missing keys, unknown columns', async () => {
    await assert.rejects(generate('cards', `${SCHEMA}.product`, 10), /page 10 already exists/);
    await assert.rejects(generate('cards', `${SCHEMA}.product`, 30, { title: 'nope' }), /"nope" is not a column of wiz32\.product/);
    await assert.rejects(generate('form', `${SCHEMA}.nokey`, 30), /single-column primary key/);
    await assert.rejects(generate('cards', `${SCHEMA}.product_v`, 30, { form_page: 31 }), /single-column primary key/);
    await assert.rejects(generate('master_detail', `${SCHEMA}.product`, 30), /no detail table/);
    await assert.rejects(generate('cards', `${SCHEMA}.product`, 30, { form_page: 30 }), /page number of its own/);
    // a view works without a form
    await generate('cards', `${SCHEMA}.product_v`, 30);
    assert.match((await regions(30))[0].source, /t\.name as title/);
  });
});

describe('builder', () => {
  test('step 1 lists the page types; step 2 proposes the defaults; the POST creates the pages', async () => {
    const b = await builder();
    const home = (await b.get(`/builder/apps/${appId}`)).body;
    assert.match(home, new RegExp(`<form method="get" action="/builder/apps/${appId}/wizard">`));
    for (const k of ['Cards', 'Calendar', 'Chart', 'Map', 'Faceted search', 'Form', 'Master detail', 'Report and form', 'Interactive grid'])
      assert.match(home, new RegExp(`<option value="[a-z_]+"( selected)?>${k}</option>`));
    const step2 = (await b.get(`/builder/apps/${appId}/wizard?kind=calendar&table=${SCHEMA}.meeting`)).body;
    assert.match(step2, /<option value="starts_at" selected>/);
    assert.match(step2, /name="drag"/);
    assert.match(step2, /<form method="post" action="\/builder\/apps\/\d+\/wizard">/);
    const res = await b.submit(`/builder/apps/${appId}/wizard`, { ...formFields(step2.replace(`<form method="post" action="/builder/apps/${appId}/wizard"`, '<form method="post" class="page-form"')), report_page: '40', nav: 'true' });
    assert.equal(res.statusCode, 303);
    assert.match(res.headers.location as string, /^\/builder\/pages\/\d+$/, [...((await b.get(res.headers.location as string)).body).matchAll(/class="alert[^>]*>([^<]*)/g)].map((m) => m[1]).join(' | '));
    assert.equal((await regions(40))[0].type, 'calendar');
    // master-detail: the detail table is a choice among the referencing tables
    const md = (await b.get(`/builder/apps/${appId}/wizard?kind=master_detail&table=${SCHEMA}.category`)).body;
    assert.match(md, /<option value="wiz32\.product\|category_id" selected>/);
    // facets and columns as checkboxes; unchecked ones are left out
    await b.get(`/builder/apps/${appId}/wizard?kind=facets&table=${SCHEMA}.product`);
    assert.equal((await b.submit(`/builder/apps/${appId}/wizard`, { kind: 'facets', table: `${SCHEMA}.product`, report_page: '41', label: 'Shop', icon: 'filter', columns: ['name', 'price'], facets: ['price'], search: 'true' })).statusCode, 303);
    const rs = await regions(41);
    assert.deepEqual(rs[0].config.facets, [{ column: 'price', label: 'Price', type: 'range', custom: true }]);
    assert.match(rs[1].source, /select t\.id,\s+t\.name,\s+t\.price\s/);
    assert.equal((await owner.one(`select count(*)::int as n from meta.nav_entry where app_id = $1 and target_page = 41`, [appId])).n, 0, 'nav unchecked');
    // an error goes back to step 2 with the message
    const bad = await b.submit(`/builder/apps/${appId}/wizard`, { kind: 'cards', table: `${SCHEMA}.product`, report_page: '41', title: 'name' });
    assert.equal(bad.headers.location, `/builder/apps/${appId}/wizard?kind=cards&table=${SCHEMA}.product`);
    assert.match((await b.get(bad.headers.location as string)).body, /page 41 already exists/);
    // the older one-step form still works for report and form
    await b.get(`/builder/apps/${appId}`);
    assert.equal((await b.submit(`/builder/apps/${appId}/wizard`, { kind: 'report_form', table: `${SCHEMA}.category`, report_page: '42', form_page: '43', label: '', icon: 'table' })).statusCode, 303);
    assert.deepEqual((await regions(42)).map((r) => r.type), ['report']);
  });

  test('wizardOptions keeps only known values', () => {
    const o = wizardOptions('chart', { chart: 'gauge"', function: 'pg_sleep', label_column: 'x', icon: '"><script>' });
    assert.equal(o.chart, 'bar');
    assert.equal(o.function, 'count');
    assert.equal(o.icon, null);
    assert.throws(() => wizardOptions('cards', { form_page: '1; drop table x' }), /not a page number/);
    assert.deepEqual(wizardOptions('master_detail', { detail: 'a.b|c' }), { label: null, icon: null, nav: false, detail: 'a.b', detail_column: 'c' });
  });
});
