// Quick SQL (src/quicksql.ts) and the SQL script splitter (src/sqlscript.ts): pure unit tests.
import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { inferColumnType, parseQuickSql, qid, qsName, quickSql, singular } from '../src/quicksql.ts';
import { splitScript } from '../src/sqlscript.ts';

describe('splitScript', () => {
  test('splits at semicolons outside strings, identifiers, comments and dollar quotes', () => {
    const s = splitScript(`-- header; not a statement
create table t (a text); insert into t values ('a;b'), (E'it\\'s;'), ($q$x;y$q$);
select "we;ird" from t /* c; d */ ;
do $body$ begin raise notice 'x;'; end $body$;
`);
    assert.deepEqual(
      s.map((x) => x.sql),
      [
        'create table t (a text)',
        `insert into t values ('a;b'), (E'it\\'s;'), ($q$x;y$q$)`,
        'select "we;ird" from t /* c; d */',
        "do $body$ begin raise notice 'x;'; end $body$",
      ],
    );
    assert.deepEqual(s.map((x) => x.line), [2, 2, 3, 4]);
  });

  test('nested block comments and empty statements', () => {
    assert.deepEqual(splitScript('/* a /* b; */ c; */ select 1;;\n;  -- x;\n').map((x) => x.sql), ['select 1']);
    assert.deepEqual(splitScript(''), []);
    assert.deepEqual(splitScript('  -- only a comment\n'), []);
  });

  test('a statement without a final semicolon', () => {
    assert.deepEqual(splitScript('select 1;\nselect 2').map((x) => x.sql), ['select 1', 'select 2']);
  });

  test('$ inside identifiers is not a dollar quote; $1 is not either', () => {
    assert.deepEqual(splitScript('create table a$b$ (x int); select $1; select 2;').map((x) => x.sql), ['create table a$b$ (x int)', 'select $1', 'select 2']);
  });

  test('BEGIN ATOMIC function bodies stay one statement', () => {
    const s = splitScript(`create function f(x int) returns int language sql
begin atomic
  select case when x > 0 then 1 else 0 end;
  select 2;
end;
select f(1);
begin; commit;`);
    assert.equal(s.length, 4);
    assert.match(s[0].sql, /^create function[\s\S]*select 2;\nend$/);
    assert.deepEqual(s.slice(1).map((x) => x.sql), ['select f(1)', 'begin', 'commit']);
  });

  test('psql meta-commands end at the line break and are marked', () => {
    const s = splitScript('\\set ON_ERROR_STOP on\nselect 1;\n  \\echo done\nselect 2;');
    assert.deepEqual(s, [
      { sql: '\\set ON_ERROR_STOP on', line: 1, psql: true },
      { sql: 'select 1', line: 2 },
      { sql: '\\echo done', line: 3, psql: true },
      { sql: 'select 2', line: 4 },
    ]);
    // a backslash inside a statement is not a meta-command
    assert.deepEqual(splitScript("select '\\x'\n, 1;").map((x) => x.sql), ["select '\\x'\n, 1"]);
  });

  test('an unterminated string or dollar quote swallows the rest (as psql does)', () => {
    assert.deepEqual(splitScript("select 'a; select 2;").map((x) => x.sql), ["select 'a; select 2;"]);
    assert.deepEqual(splitScript('do $$ begin; select 2;').map((x) => x.sql), ['do $$ begin; select 2;']);
  });
});

describe('Quick SQL names and types', () => {
  test('names', () => {
    assert.equal(qsName('Cost Center'), 'cost_center');
    assert.equal(qsName('Größe'), 'grosse');
    assert.equal(qsName('1st place'), 'x_1st_place');
    assert.equal(qsName('a; drop table x'), 'a_drop_table_x');
    assert.equal(qid('order'), '"order"');
    assert.equal(qid('name'), 'name');
    assert.equal(singular('departments'), 'department');
    assert.equal(singular('categories'), 'category');
    assert.equal(singular('boxes'), 'box');
    assert.equal(singular('status'), 'status');
    assert.equal(singular('address'), 'address');
  });

  test('types inferred from names', () => {
    const cases: Record<string, string> = {
      dept_id: 'bigint',
      created_at: 'timestamptz',
      hire_date: 'date',
      date_of_birth: 'date',
      is_active: 'boolean',
      active_yn: 'boolean',
      salary: 'numeric',
      unit_price: 'numeric',
      item_count: 'integer',
      name: 'text',
      settings_json: 'jsonb',
    };
    for (const [n, t] of Object.entries(cases)) assert.equal(inferColumnType(n), t, n);
  });
});

describe('Quick SQL → DDL', () => {
  const ddl = (src: string) => quickSql(src).ddl;

  test('a table with columns, explicit types and constraints', () => {
    const r = quickSql(`products
  name /nn /unique
  code vc20 /upper /idx
  price num(10,2) /nn /default 0
  weight num /between 0 and 1000
  status /check new, sold, archived /default new
  notes clob [free text]
  added_at
  in_stock bool /default y`);
    assert.deepEqual(r.warnings, []);
    assert.match(r.ddl, /create table products \(\n {4}id +bigint generated by default as identity primary key,/);
    assert.match(r.ddl, /name +text not null unique,/);
    assert.match(r.ddl, /code +varchar\(20\) check \(code = upper\(code\)\),/);
    assert.match(r.ddl, /price +numeric\(10,2\) not null default 0,/);
    assert.match(r.ddl, /weight +numeric check \(weight between 0 and 1000\),/);
    assert.match(r.ddl, /status +text default 'new' check \(status in \('new', 'sold', 'archived'\)\),/);
    assert.match(r.ddl, /added_at +timestamptz,/);
    assert.match(r.ddl, /in_stock +boolean default true\n\);/);
    assert.match(r.ddl, /create index products_code_idx on products \(code\);/);
    assert.match(r.ddl, /comment on column products\.notes is 'free text';/);
  });

  test('child tables by indentation get a foreign key to their parent', () => {
    const r = quickSql(`departments
  name /nn
  employees
    name /nn
    job
    projects
      title`);
    assert.deepEqual(r.model.tables.map((t) => [t.name, t.parent]), [['departments', undefined], ['employees', 'departments'], ['projects', 'employees']]);
    assert.match(r.ddl, /department_id +bigint references departments on delete cascade/);
    assert.match(r.ddl, /employee_id +bigint references employees on delete cascade/);
    assert.match(r.ddl, /create index employees_department_id_idx on employees \(department_id\);/);
    // parents come first
    assert.ok(r.ddl.indexOf('create table departments') < r.ddl.indexOf('create table employees'));
  });

  test('a declared parent key keeps its directives', () => {
    const r = quickSql('orders\n  ref\n  order_lines\n    order_id /nn\n    qty');
    assert.match(r.ddl, /order_id +bigint not null references orders on delete cascade/);
    assert.equal(r.model.tables[1].columns.filter((c) => c.name === 'order_id').length, 1);
  });

  test('_id columns refer to tables in the model; /fk to any table; forward references become ALTER TABLE', () => {
    const r = quickSql(`employees
  name
  dept_id
  manager_id /fk employees
  country_id
depts
  name`);
    assert.match(r.ddl, /manager_id +bigint references employees/, 'self reference inline');
    assert.match(r.ddl, /alter table employees add foreign key \(dept_id\) references depts;/);
    assert.doesNotMatch(r.ddl, /country_id bigint references/);
    assert.deepEqual(r.warnings, []);
  });

  test('settings: pk, schema, prefix, drop, auditcols', () => {
    const guid = ddl('# pk: guid\nt\n  a');
    assert.match(guid, /id uuid default gen_random_uuid\(\) primary key/);
    const seq = ddl('# pk: seq\nt\n  a');
    assert.match(seq, /create sequence if not exists t_seq;/);
    assert.match(seq, /id bigint default nextval\('t_seq'\) primary key/);
    const none = ddl('# pk: none\nt\n  code /pk\n  b');
    assert.match(none, /code text primary key/);
    assert.doesNotMatch(none, /\bid\b/);
    const all = ddl('# settings = { schema: "Sales", prefix: "xx", drop: true, auditcols: true }\nt\n  a\nu\n  b');
    assert.match(all, /^drop table if exists sales\.xx_u cascade;\ndrop table if exists sales\.xx_t cascade;/);
    assert.match(all, /create schema if not exists sales;/);
    assert.match(all, /create table sales\.xx_t \(/);
    assert.match(all, /created_at +timestamptz not null default now\(\)/);
    assert.match(all, /create trigger xx_t_audit before insert or update on sales\.xx_t for each row execute function sales\.set_audit_columns\(\);/);
  });

  test('composite primary key', () => {
    assert.match(ddl('# pk: none\nlinks\n  a_id /pk\n  b_id /pk'), /primary key \(a_id, b_id\)/);
  });

  test('views join the tables by foreign keys', () => {
    const r = quickSql('depts\n  name\n  emps\n    name\nview emp_v depts emps');
    assert.match(r.ddl, /create or replace view emp_v as\nselect t1\.id as dept_id,/);
    assert.match(r.ddl, /from depts t1\n  left join emps t2 on t2\.dept_id = t1\.id;/);
  });

  test('reserved words and odd names are quoted, values are escaped', () => {
    const r = quickSql(`user
  order
  "x"; drop table t; -- /check a'b, c
  note /default it's`);
    assert.match(r.ddl, /create table "user" \(/);
    assert.match(r.ddl, /"order" +text/);
    assert.match(r.ddl, /x_drop_table_t +text/);
    assert.match(r.ddl, /note +text default 'it''s'/);
    assert.doesNotMatch(r.ddl, /drop table t;/);
  });

  test('comments, blank lines and tabs', () => {
    const r = quickSql('-- a model\n\nt -- the table\n\tname -- a column\n\n');
    assert.deepEqual(r.model.tables.map((t) => t.columns.map((c) => c.name)), [['name']]);
  });

  test('warnings for what is not understood, with line numbers', () => {
    const r = parseQuickSql('# colour: blue\nt /history\n  a /frobnicate\n  b /fk\n  c /between x and y\nview v t nope');
    assert.deepEqual(
      r.warnings.map((w) => w.line),
      [1, 2, 3, 4, 5, 6],
    );
    assert.deepEqual(parseQuickSql('').warnings.map((w) => w.line), [1]);
  });
});
