-- =====================================================================
-- Sample application "HR Demo"
--
-- Part 1: the database. Business rules live here as PL/pgSQL, where they
--         hold no matter which UI (or script) touches the data:
--   * hr.audit()               generic audit-trail trigger (jsonb diff, app user)
--   * hr.check_salary()        BEFORE trigger; its error lands on the form field
--   * hr.give_raise()          business function behind a button
--   * hr.suggest_salary()      called live from a dynamic action
--   * hr.request_leave()       validates + inserts a leave request
--   * hr.decide_leave()        approval, checks the management chain
--   * hr.notify_*()            triggers that create notifications
--   * row level security       employees see their own leave, managers their team's
-- Part 2: the application, built only with SQL against the meta schema.
-- =====================================================================

create schema hr;

create table hr.dept (
  deptno  int generated by default as identity primary key,
  dname   text not null unique,
  loc     text
);

create table hr.emp (
  empno     int generated by default as identity primary key,
  ename     text not null,
  job       text,
  mgr       int references hr.emp,
  hiredate  date not null default current_date,
  sal       numeric(9,2) check (sal >= 0),
  comm      numeric(9,2),
  deptno    int references hr.dept,
  active    boolean not null default true,
  -- links an application user to an employee
  username  text unique
);

insert into hr.dept (deptno, dname, loc) overriding system value values
  (10, 'ACCOUNTING', 'NEW YORK'), (20, 'RESEARCH', 'DALLAS'),
  (30, 'SALES', 'CHICAGO'),       (40, 'OPERATIONS', 'BOSTON');

insert into hr.emp (empno, ename, job, mgr, hiredate, sal, comm, deptno, username) overriding system value values
  (7839, 'KING',   'PRESIDENT', null, '1981-11-17', 5000, null, 10, 'king'),
  (7698, 'BLAKE',  'MANAGER',   7839, '1981-05-01', 2850, null, 30, 'blake'),
  (7782, 'CLARK',  'MANAGER',   7839, '1981-06-09', 2450, null, 10, null),
  (7566, 'JONES',  'MANAGER',   7839, '1981-04-02', 2975, null, 20, 'jones'),
  (7788, 'SCOTT',  'ANALYST',   7566, '1987-04-19', 3000, null, 20, 'scott'),
  (7902, 'FORD',   'ANALYST',   7566, '1981-12-03', 3000, null, 20, null),
  (7369, 'SMITH',  'CLERK',     7902, '1980-12-17',  800, null, 20, null),
  (7499, 'ALLEN',  'SALESMAN',  7698, '1981-02-20', 1600,  300, 30, 'allen'),
  (7521, 'WARD',   'SALESMAN',  7698, '1981-02-22', 1250,  500, 30, null),
  (7654, 'MARTIN', 'SALESMAN',  7698, '1981-09-28', 1250, 1400, 30, null),
  (7844, 'TURNER', 'SALESMAN',  7698, '1981-09-08', 1500,    0, 30, null),
  (7876, 'ADAMS',  'CLERK',     7788, '1987-05-23', 1100, null, 20, null),
  (7900, 'JAMES',  'CLERK',     7698, '1981-12-03',  950, null, 30, null),
  (7934, 'MILLER', 'CLERK',     7782, '1982-01-23', 1300, null, 10, null);

select setval(pg_get_serial_sequence('hr.dept', 'deptno'), 40),
       setval(pg_get_serial_sequence('hr.emp', 'empno'), 8000);

create table hr.leave_request (
  id            int generated always as identity primary key,
  empno         int  not null references hr.emp on delete cascade,
  start_date    date not null,
  end_date      date not null,
  days          int  not null,
  reason        text,
  status        text not null default 'PENDING'
                check (status in ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN')),
  decided_by    text,
  decided_at    timestamptz,
  decision_note text,
  created_at    timestamptz not null default now(),
  check (end_date >= start_date)
);

create table hr.notification (
  id          int generated always as identity primary key,
  username    text not null,
  message     text not null,
  created_at  timestamptz not null default now(),
  read_at     timestamptz
);

create table hr.audit_log (
  id          bigint generated always as identity primary key,
  table_name  text not null,
  row_pk      text,
  action      text not null,
  changed_by  text not null,
  changed_at  timestamptz not null default now(),
  old_values  jsonb,
  new_values  jsonb
);

-- ---------------------------------------------------------------------
-- Helper functions
-- ---------------------------------------------------------------------

-- The employee record of the signed-in application user.
create function hr.current_empno() returns int
language sql stable as $$
  select empno from hr.emp where lower(username) = lower(meta.app_user())
$$;

-- Is the signed-in user somewhere above p_empno in the management chain?
create function hr.is_manager_of(p_empno int) returns boolean
language sql stable as $$
  with recursive chain (empno, mgr) as (
    select empno, mgr from hr.emp where empno = p_empno
    union all
    select e.empno, e.mgr from hr.emp e join chain c on e.empno = c.mgr
  ) cycle empno set is_cycle using path
  select exists (select 1 from chain where empno <> p_empno and empno = hr.current_empno())
$$;

create function hr.business_days(p_from date, p_to date) returns int
language sql immutable as $$
  select count(*)::int
    from generate_series(p_from, p_to, interval '1 day') d
   where extract(isodow from d) < 6
$$;

-- Used by a dynamic action: typical salary for a job.
create function hr.suggest_salary(p_job text) returns numeric
language sql stable as $$
  select round(avg(sal), -1) from hr.emp where job = upper(p_job)
$$;

-- ---------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------

-- Generic audit trail. meta.app_user() carries the application user into
-- the database session, so triggers know WHO made the change, not just
-- which database role. For updates only changed columns are stored.
create function hr.audit() returns trigger
language plpgsql security definer set search_path = hr, pg_catalog as $$
declare
  v_old jsonb := case when tg_op <> 'INSERT' then to_jsonb(old) end;
  v_new jsonb := case when tg_op <> 'DELETE' then to_jsonb(new) end;
  v_pk  text  := coalesce(v_new, v_old) ->> tg_argv[0];
begin
  if tg_op = 'UPDATE' then
    select jsonb_object_agg(n.key, n.value) into v_new
      from jsonb_each(to_jsonb(new)) n
     where n.value is distinct from v_old -> n.key;
    if v_new is null then
      return new;  -- nothing changed
    end if;
    select jsonb_object_agg(o.key, o.value) into v_old
      from jsonb_each(to_jsonb(old)) o
     where v_new ? o.key;
  end if;
  insert into hr.audit_log (table_name, row_pk, action, changed_by, old_values, new_values)
  values (tg_table_name, v_pk, tg_op, meta.app_user(), v_old, v_new);
  return coalesce(new, old);
end
$$;

create trigger emp_audit after insert or update or delete on hr.emp
  for each row execute function hr.audit('empno');
create trigger dept_audit after insert or update or delete on hr.dept
  for each row execute function hr.audit('deptno');
create trigger leave_audit after insert or update or delete on hr.leave_request
  for each row execute function hr.audit('id');

-- A business rule enforced in the database. "using column" tells the
-- runtime which form field to attach the message to (the item whose
-- source column is sal), just like a validation.
create function hr.check_salary() returns trigger
language plpgsql as $$
declare
  v_max numeric;
begin
  if new.job is distinct from 'PRESIDENT' and new.sal is not null then
    select max(sal) into v_max from hr.emp where job = 'PRESIDENT' and empno <> new.empno;
    if new.sal >= v_max then
      raise exception 'Salary must stay below the president''s salary (%).', v_max
        using column = 'sal';
    end if;
  end if;
  return new;
end
$$;

create trigger emp_check_salary before insert or update of sal, job on hr.emp
  for each row execute function hr.check_salary();

-- Notifications are written for OTHER users, which the notification RLS
-- policy would forbid; security definer runs the insert as the table owner.
create function hr.notify_leave_requested() returns trigger
language plpgsql security definer set search_path = hr, pg_catalog as $$
begin
  insert into hr.notification (username, message)
  select m.username, format('%s requested %s day(s) of leave from %s.',
                            e.ename, new.days, to_char(new.start_date, 'DD Mon YYYY'))
    from hr.emp e join hr.emp m on m.empno = e.mgr
   where e.empno = new.empno and m.username is not null;
  return new;
end
$$;

create function hr.notify_leave_decided() returns trigger
language plpgsql security definer set search_path = hr, pg_catalog as $$
begin
  if new.status in ('APPROVED', 'REJECTED') then
    insert into hr.notification (username, message)
    select e.username, format('Your leave from %s to %s was %s by %s.',
                              to_char(new.start_date, 'DD Mon'), to_char(new.end_date, 'DD Mon'),
                              lower(new.status), new.decided_by)
      from hr.emp e
     where e.empno = new.empno and e.username is not null;
  end if;
  return new;
end
$$;

create trigger leave_requested after insert on hr.leave_request
  for each row execute function hr.notify_leave_requested();
create trigger leave_decided after update of status on hr.leave_request
  for each row when (old.status is distinct from new.status)
  execute function hr.notify_leave_decided();

-- ---------------------------------------------------------------------
-- Business functions called from the application
-- ---------------------------------------------------------------------

-- Button "Give 10% raise" (page 3).
create function hr.give_raise(p_empno int, p_pct numeric) returns numeric
language plpgsql as $$
declare
  v_sal numeric;
begin
  if not (meta.has_role('manager') or meta.has_role('admin')) then
    raise exception 'Only managers can give raises.';
  end if;
  if p_pct <= 0 or p_pct > 20 then
    raise exception 'A raise must be between 0 and 20 percent.';
  end if;
  if p_empno = hr.current_empno() then
    raise exception 'You cannot give yourself a raise.';
  end if;
  update hr.emp set sal = round(sal * (1 + p_pct / 100), 2)
   where empno = p_empno
  returning sal into v_sal;
  if not found then
    raise exception 'Employee % not found.', p_empno;
  end if;
  return v_sal;
end
$$;

-- Button "Submit request" (page 7).
create function hr.request_leave(p_start date, p_end date, p_reason text) returns int
language plpgsql as $$
declare
  v_empno int := hr.current_empno();
  v_days  int;
  v_used  int;
  v_id    int;
begin
  if v_empno is null then
    raise exception 'Your account is not linked to an employee, so you cannot request leave.';
  end if;
  if p_start < current_date then
    raise exception 'Leave cannot start in the past.' using column = 'start_date';
  end if;
  if p_end < p_start then
    raise exception 'The end date must be on or after the start date.' using column = 'end_date';
  end if;
  v_days := hr.business_days(p_start, p_end);
  if v_days = 0 then
    raise exception 'The selected period contains no working days.' using column = 'end_date';
  end if;
  if exists (select 1 from hr.leave_request
              where empno = v_empno and status in ('PENDING', 'APPROVED')
                and daterange(start_date, end_date, '[]') && daterange(p_start, p_end, '[]')) then
    raise exception 'This period overlaps with another leave request.';
  end if;
  select coalesce(sum(days), 0) into v_used
    from hr.leave_request
   where empno = v_empno and status = 'APPROVED'
     and extract(year from start_date) = extract(year from p_start);
  if v_used + v_days > 25 then
    raise exception 'Not enough leave left: % of 25 days used this year, % requested.', v_used, v_days;
  end if;

  insert into hr.leave_request (empno, start_date, end_date, days, reason)
  values (v_empno, p_start, p_end, v_days, p_reason)
  returning id into v_id;
  return v_id;
end
$$;

-- Buttons "Approve" / "Reject" (page 7).
create function hr.decide_leave(p_id int, p_decision text, p_note text default null) returns void
language plpgsql as $$
declare
  r hr.leave_request;
begin
  if p_decision not in ('APPROVED', 'REJECTED') then
    raise exception 'Invalid decision %.', p_decision;
  end if;
  select * into r from hr.leave_request where id = p_id for update;
  if not found then
    raise exception 'Leave request % not found.', p_id;
  end if;
  if r.status <> 'PENDING' then
    raise exception 'This request has already been %.', lower(r.status);
  end if;
  if r.empno = hr.current_empno() then
    raise exception 'You cannot decide on your own leave request.';
  end if;
  if not (hr.is_manager_of(r.empno) or meta.has_role('admin')) then
    raise exception 'Only a manager of this employee can decide on the request.';
  end if;
  update hr.leave_request
     set status = p_decision, decided_by = meta.app_user(), decided_at = now(), decision_note = p_note
   where id = p_id;
end
$$;

-- Button "Withdraw" (page 7).
create function hr.withdraw_leave(p_id int) returns void
language plpgsql as $$
begin
  update hr.leave_request set status = 'WITHDRAWN'
   where id = p_id and status = 'PENDING' and empno = hr.current_empno();
  if not found then
    raise exception 'Only your own pending requests can be withdrawn.';
  end if;
end
$$;

-- ---------------------------------------------------------------------
-- Security: the app's database role + row level security
-- ---------------------------------------------------------------------

create role hr_app nologin;
grant hr_app to pgkiln_runtime;          -- lets the runtime SET ROLE hr_app
grant usage on schema hr to hr_app;
grant select, insert, update, delete on hr.emp, hr.dept to hr_app;
grant select, insert, update on hr.leave_request to hr_app;
grant select, update (read_at) on hr.notification to hr_app;
grant select on hr.audit_log to hr_app;
grant execute on all functions in schema hr to hr_app;

alter table hr.leave_request enable row level security;
create policy leave_visible on hr.leave_request for select
  using (empno = hr.current_empno() or hr.is_manager_of(empno) or meta.has_role('admin'));
create policy leave_insert on hr.leave_request for insert
  with check (empno = hr.current_empno());
create policy leave_update on hr.leave_request for update
  using (empno = hr.current_empno() or hr.is_manager_of(empno) or meta.has_role('admin'));

alter table hr.notification enable row level security;
create policy own_notifications on hr.notification
  using (lower(username) = lower(meta.app_user()));

alter table hr.audit_log enable row level security;
create policy admins_only on hr.audit_log for select using (meta.has_role('admin'));

-- =====================================================================
-- Part 2: the application definition
-- =====================================================================

insert into meta.app (alias, name, home_page, authentication, db_role, debug)
values ('hr', 'HR Demo', 1, 'app_users', 'hr_app', false);

insert into meta.app_user (app_id, username, password_hash, roles)
select a.id, u.username, meta.hash_password(u.username), u.roles
  from meta.app a,
       (values ('demo', '{admin}'::text[]), ('king', '{admin,manager}'), ('blake', '{manager}'),
               ('jones', '{manager}'), ('allen', '{}'), ('scott', '{}')) u(username, roles)
 where a.alias = 'hr';

-- Shared components ---------------------------------------------------

insert into meta.authz_scheme (app_id, name, type, value, error_message)
select a.id, x.name, x.type, x.value, x.msg from meta.app a, (values
  ('ADMIN', 'role', 'admin', 'Only administrators can access this page.'),
  ('MANAGER', 'sql', 'meta.has_role(''manager'') or meta.has_role(''admin'')', 'Only managers can access this page.')
) x(name, type, value, msg) where a.alias = 'hr';

insert into meta.app_item (app_id, name, description)
select a.id, x.name, x.d from meta.app a, (values
  ('AI_EMPNO', 'Employee number of the signed-in user'),
  ('AI_ENAME', 'Employee name of the signed-in user')
) x(name, d) where a.alias = 'hr';

insert into meta.app_process (app_id, seq, name, point, code)
select id, 10, 'Link user to employee', 'after_login',
       E'select (select empno from hr.emp where lower(username) = lower(:APP_USER)) as ai_empno,\n       coalesce((select initcap(ename) from hr.emp where lower(username) = lower(:APP_USER)), :APP_USER) as ai_ename'
  from meta.app where alias = 'hr';

-- Pages 2+3 and 4+5 come from the CRUD wizard (which also adds menu entries).
select meta.generate_crud('hr', 'hr.emp', 2, 3, 'Employees', 'users');
select meta.generate_crud('hr', 'hr.dept', 4, 5, 'Departments', 'building');

-- Page 1: dashboard ----------------------------------------------------
insert into meta.page (app_id, page_no, name, title)
select id, 1, 'Dashboard', 'Dashboard' from meta.app where alias = 'hr';

insert into meta.region (page_id, seq, title, type, columns, template, source, config)
select p.id, r.seq, r.title, r.type, r.cols, r.template, r.source, r.config::jsonb
  from meta.page p join meta.app a on a.id = p.app_id, (values
  (10, null, 'static', 12, 'plain',
   '<p class="lead">Welcome back, <b>&AI_ENAME.</b>. Everything on this page is a row in the <code>meta</code> schema; the numbers respect row level security.</p>',
   '{}'),
  (20, 'Key figures', 'cards', 12, 'plain',
   E'select ''Employees'' as title, count(*)::text as badge, ''users'' as icon from hr.emp where active\nunion all\nselect ''Monthly payroll'', to_char(sum(sal), ''FM999G999''), ''chart'' from hr.emp where active\nunion all\nselect ''Departments'', count(*)::text, ''building'' from hr.dept\nunion all\nselect ''Pending leave (visible to you)'', count(*)::text, ''calendar'' from hr.leave_request where status = ''PENDING''',
   '{"style": "metric"}'),
  (30, 'Headcount by department', 'chart', 6, 'standard',
   E'select d.dname, count(e.empno)\n  from hr.dept d left join hr.emp e on e.deptno = d.deptno\n group by d.dname\n order by 2 desc',
   '{}'),
  (40, 'Salary budget by job', 'chart', 6, 'standard',
   E'select job, sum(sal) from hr.emp group by job order by 2 desc',
   '{}'),
  (50, 'My notifications', 'report', 7, 'standard',
   E'select concat(case when read_at is null then ''● '' end, message) as message, created_at as received\n  from hr.notification\n order by created_at desc\n limit 8',
   '{"searchable": false, "sortable": false, "page_size": 8, "empty": "No notifications."}'),
  (60, 'Most recent hires', 'report', 5, 'standard',
   E'select e.ename as name, d.dname as department, e.hiredate\n  from hr.emp e left join hr.dept d using (deptno)\n order by e.hiredate desc\n limit 5',
   '{"searchable": false, "sortable": false}')
) as r(seq, title, type, cols, template, source, config)
 where a.alias = 'hr' and p.page_no = 1;

insert into meta.button (page_id, region_id, seq, name, label, action, condition)
select p.id, r.id, 10, 'MARK_READ', 'Mark all read', 'submit',
       'exists (select 1 from hr.notification where read_at is null)'
  from meta.page p join meta.app a on a.id = p.app_id join meta.region r on r.page_id = p.id and r.title = 'My notifications'
 where a.alias = 'hr' and p.page_no = 1;

insert into meta.process (page_id, name, type, code, when_button, success_message)
select p.id, 'Mark notifications read', 'sql', 'update hr.notification set read_at = now() where read_at is null',
       'MARK_READ', 'Notifications marked as read.'
  from meta.page p join meta.app a on a.id = p.app_id where a.alias = 'hr' and p.page_no = 1;

-- Page 2: employees report with a department filter ------------------------
update meta.region r
   set source = E'select e.empno, e.ename, e.job, d.dname as department, e.hiredate, e.sal, e.active\n  from hr.emp e\n  left join hr.dept d on d.deptno = e.deptno\n where :P2_DEPTNO is null or e.deptno = :P2_DEPTNO::int',
       config = r.config || '{"headings": {"empno": "No.", "ename": "Name", "sal": "Salary"}}'
  from meta.page p, meta.app a
 where r.page_id = p.id and p.app_id = a.id and a.alias = 'hr' and p.page_no = 2 and r.type = 'report';

insert into meta.item (page_id, region_id, seq, name, label, type, lov, config)
select p.id, r.id, 5, 'P2_DEPTNO', 'Department', 'select',
       'select dname, deptno from hr.dept order by 1',
       '{"submit_on_change": true, "null_label": "- All departments -"}'
  from meta.page p
  join meta.app a on a.id = p.app_id
  join meta.region r on r.page_id = p.id and r.type = 'report'
 where a.alias = 'hr' and p.page_no = 2;

-- Page 3: employee form (modal) --------------------------------------------
update meta.page p set authz = 'MANAGER'
  from meta.app a where a.id = p.app_id and a.alias = 'hr' and p.page_no = 3;

update meta.item i set label = v.label, lov = coalesce(v.lov, i.lov), type = coalesce(v.type, i.type),
                       config = i.config || v.config::jsonb, help = v.help
  from meta.page p, meta.app a,
       (values ('P3_ENAME', 'Name', null, null, '{}', null),
               ('P3_JOB', 'Job', 'STATIC:President;PRESIDENT,Manager;MANAGER,Analyst;ANALYST,Salesman;SALESMAN,Clerk;CLERK', 'select', '{}',
                'Choosing a job suggests a salary (dynamic action calling hr.suggest_salary).'),
               ('P3_MGR', 'Manager',
                E'select ename || '' ('' || initcap(job) || '')'', empno\n  from hr.emp\n where (:P3_DEPTNO is null or deptno = :P3_DEPTNO::int or job = ''PRESIDENT'')\n   and empno is distinct from :P3_EMPNO::int\n order by ename',
                'select', '{"cascade_parents": "P3_DEPTNO"}', 'Filtered by department (cascading list of values).'),
               ('P3_HIREDATE', 'Hire date', null, null, '{}', null),
               ('P3_SAL', 'Salary', null, null, '{}', 'A database trigger keeps salaries below the president''s.'),
               ('P3_COMM', 'Commission', null, null, '{}', null),
               ('P3_DEPTNO', 'Department', null, null, '{}', null),
               ('P3_USERNAME', 'App username', null, null, '{}', 'Links an application user to this employee.')
       ) v(name, label, lov, type, config, help)
 where i.page_id = p.id and p.app_id = a.id and a.alias = 'hr' and p.page_no = 3 and i.name = v.name;

-- reorder: department before manager (the manager list depends on it)
update meta.item i set seq = 35
  from meta.page p, meta.app a
 where i.page_id = p.id and p.app_id = a.id and a.alias = 'hr' and p.page_no = 3 and i.name = 'P3_DEPTNO';

insert into meta.validation (page_id, seq, name, item_name, type, expression, message)
select p.id, 10, 'Commission only for sales', 'P3_COMM', 'sql',
       ':P3_COMM is null or :P3_COMM::numeric = 0 or :P3_JOB = ''SALESMAN''',
       'Only salesmen can earn commission.'
  from meta.page p join meta.app a on a.id = p.app_id
 where a.alias = 'hr' and p.page_no = 3;

insert into meta.button (page_id, region_id, seq, name, label, action, target_page, condition, authz)
select p.id, r.id, 25, 'RAISE', 'Give 10% raise', 'submit', 2, ':P3_EMPNO is not null', 'MANAGER'
  from meta.page p join meta.app a on a.id = p.app_id
  join meta.region r on r.page_id = p.id and r.type = 'form'
 where a.alias = 'hr' and p.page_no = 3;

update meta.button b set authz = 'ADMIN'
  from meta.page p, meta.app a
 where b.page_id = p.id and p.app_id = a.id and a.alias = 'hr' and p.page_no = 3 and b.name = 'DELETE';

insert into meta.process (page_id, seq, name, type, code, when_button, success_message)
select p.id, 20, 'Give raise', 'sql',
       'select hr.give_raise(:P3_EMPNO::int, 10) as p3_sal', 'RAISE', 'Salary raised by 10%.'
  from meta.page p join meta.app a on a.id = p.app_id
 where a.alias = 'hr' and p.page_no = 3;

insert into meta.dynamic_action (page_id, seq, name, event, trigger_element, condition_type, condition_value,
                                 action, affected_items, code, items_to_submit)
select p.id, d.seq, d.name, 'change', d.trig, d.ctype, d.cval, d.action, d.affected, d.code, d.submit
  from meta.page p join meta.app a on a.id = p.app_id, (values
  (10, 'Commission only for salesmen', 'P3_JOB', 'equals', 'SALESMAN', 'show', 'P3_COMM', null, null),
  (20, 'Suggest a salary for the job', 'P3_JOB', 'is_not_null', null, 'set_value', 'P3_SAL',
   'select coalesce(:P3_SAL::numeric, hr.suggest_salary(:P3_JOB))', 'P3_JOB,P3_SAL')
) d(seq, name, trig, ctype, cval, action, affected, code, submit)
 where a.alias = 'hr' and p.page_no = 3;

-- Pages 4/5: departments as cards; editing requires ADMIN -------------------
update meta.region r
   set type = 'cards',
       source = E'select d.dname as title, initcap(d.loc) as subtitle,\n       count(e.empno) || '' employees · payroll '' || coalesce(to_char(sum(e.sal), ''FM999G999''), ''0'') as body,\n       d.deptno as badge, ''building'' as icon, d.deptno\n  from hr.dept d left join hr.emp e on e.deptno = d.deptno\n group by d.deptno\n order by d.dname',
       config = '{"link": {"page": 5, "items": {"P5_DEPTNO": "#deptno#"}}}'
  from meta.page p, meta.app a
 where r.page_id = p.id and p.app_id = a.id and a.alias = 'hr' and p.page_no = 4;

update meta.button b set authz = 'ADMIN'
  from meta.page p, meta.app a
 where b.page_id = p.id and p.app_id = a.id and a.alias = 'hr' and p.page_no = 4;
update meta.page p set authz = 'ADMIN'
  from meta.app a where a.id = p.app_id and a.alias = 'hr' and p.page_no = 5;

-- Page 8: org chart (recursive CTE) ----------------------------------------
insert into meta.page (app_id, page_no, name, title, parent_page)
select id, 8, 'Org chart', 'Organization chart', 2 from meta.app where alias = 'hr';

insert into meta.region (page_id, seq, title, type, source, config)
select p.id, 10, 'Reporting lines', 'report',
       E'with recursive tree as (\n  select empno, ename, job, 1 as lvl, array[ename] as path from hr.emp where mgr is null\n  union all\n  select e.empno, e.ename, e.job, t.lvl + 1, t.path || e.ename\n    from hr.emp e join tree t on e.mgr = t.empno\n)\nselect repeat(''    '', lvl - 1) || case when lvl > 1 then ''└ '' else '''' end || ename as employee,\n       initcap(job) as job,\n       (select count(*) from hr.emp x where x.mgr = tree.empno) as direct_reports\n  from tree\n order by path',
       '{"sortable": false, "searchable": false, "page_size": 50, "preformatted": ["employee"]}'
  from meta.page p join meta.app a on a.id = p.app_id where a.alias = 'hr' and p.page_no = 8;

-- Pages 6/7: leave requests (RLS + PL/pgSQL workflow) ------------------------
insert into meta.page (app_id, page_no, name, title, parent_page)
select id, 6, 'Leave requests', 'Leave requests', 1 from meta.app where alias = 'hr';
insert into meta.page (app_id, page_no, name, title, parent_page, mode)
select id, 7, 'Leave request', 'Leave request', 6, 'modal' from meta.app where alias = 'hr';

insert into meta.region (page_id, seq, title, type, source, config)
select p.id, 10, 'Requests you can see', 'report',
       E'select l.id, e.ename as employee, l.start_date, l.end_date, l.days, l.status, l.decided_by, l.created_at as requested\n  from hr.leave_request l\n  join hr.emp e using (empno)\n where :P6_STATUS is null or l.status = :P6_STATUS\n order by l.created_at desc',
       '{"link": {"column": "id", "page": 7, "items": {"P7_ID": "#id#"}}, "empty": "No leave requests visible to you."}'
  from meta.page p join meta.app a on a.id = p.app_id where a.alias = 'hr' and p.page_no = 6;

insert into meta.item (page_id, region_id, seq, name, label, type, lov, config)
select p.id, r.id, 5, 'P6_STATUS', 'Status', 'select',
       'STATIC:Pending;PENDING,Approved;APPROVED,Rejected;REJECTED,Withdrawn;WITHDRAWN',
       '{"submit_on_change": true, "null_label": "- Any status -"}'
  from meta.page p join meta.app a on a.id = p.app_id join meta.region r on r.page_id = p.id
 where a.alias = 'hr' and p.page_no = 6;

insert into meta.button (page_id, region_id, seq, name, label, action, target_page, hot)
select p.id, r.id, 10, 'NEW', 'Request leave', 'redirect', 7, true
  from meta.page p join meta.app a on a.id = p.app_id join meta.region r on r.page_id = p.id
 where a.alias = 'hr' and p.page_no = 6;

insert into meta.region (page_id, seq, title, type, table_name, pk_column, pk_item, template)
select p.id, 10, 'Leave request', 'form', 'hr.leave_request', 'id', 'P7_ID', 'plain'
  from meta.page p join meta.app a on a.id = p.app_id where a.alias = 'hr' and p.page_no = 7;

insert into meta.item (page_id, region_id, seq, name, label, type, lov, source_column, required,
                       readonly_condition, authz, help)
select p.id, r.id, i.seq, i.name, i.label, i.type, i.lov, i.col, i.req, i.ro, i.auth, i.help
  from meta.page p join meta.app a on a.id = p.app_id join meta.region r on r.page_id = p.id, (values
  (10, 'P7_ID', null, 'hidden', null, 'id', false, null, null, null),
  (20, 'P7_EMPNO', 'Employee', 'display', 'select ename, empno from hr.emp', 'empno', false, null, null, null),
  (30, 'P7_START_DATE', 'From', 'date', null, 'start_date', true, ':P7_ID is not null', null, null),
  (40, 'P7_END_DATE', 'Until', 'date', null, 'end_date', true, ':P7_ID is not null', null, null),
  (50, 'P7_DAYS', 'Working days', 'display', null, 'days', false, null, null, 'Calculated by hr.business_days() as you pick dates.'),
  (60, 'P7_STATUS', 'Status', 'display', null, 'status', false, null, null, null),
  (70, 'P7_REASON', 'Reason', 'textarea', null, 'reason', false, ':P7_ID is not null', null, null),
  (80, 'P7_DECIDED_BY', 'Decided by', 'display', null, 'decided_by', false, null, null, null),
  (90, 'P7_DECISION_NOTE', 'Decision note', 'textarea', null, 'decision_note', false,
   ':P7_ID is null or :P7_STATUS <> ''PENDING''', 'MANAGER', null)
) i(seq, name, label, type, lov, col, req, ro, auth, help)
 where a.alias = 'hr' and p.page_no = 7;

insert into meta.button (page_id, region_id, seq, name, label, action, target_page, condition, authz, hot, confirm)
select p.id, r.id, b.seq, b.name, b.label, b.action, 6, b.cond, b.auth, b.hot, b.confirm
  from meta.page p join meta.app a on a.id = p.app_id join meta.region r on r.page_id = p.id, (values
  (10, 'CANCEL', 'Close', 'redirect', null, null, false, null),
  (20, 'WITHDRAW', 'Withdraw', 'submit', ':P7_STATUS = ''PENDING'' and :P7_EMPNO::int = hr.current_empno()', null, false, 'Withdraw this request?'),
  (30, 'REJECT', 'Reject', 'submit', ':P7_STATUS = ''PENDING'' and :P7_EMPNO::int is distinct from hr.current_empno()', 'MANAGER', false, null),
  (40, 'APPROVE', 'Approve', 'submit', ':P7_STATUS = ''PENDING'' and :P7_EMPNO::int is distinct from hr.current_empno()', 'MANAGER', true, null),
  (50, 'CREATE', 'Submit request', 'submit', ':P7_ID is null', null, true, null)
) b(seq, name, label, action, cond, auth, hot, confirm)
 where a.alias = 'hr' and p.page_no = 7;

insert into meta.process (page_id, seq, name, type, code, when_button, success_message)
select p.id, x.seq, x.name, 'sql', x.code, x.btn, x.msg
  from meta.page p join meta.app a on a.id = p.app_id, (values
  (10, 'Request leave', 'select hr.request_leave(:P7_START_DATE::date, :P7_END_DATE::date, :P7_REASON) as p7_id', 'CREATE', 'Leave request submitted; your manager has been notified.'),
  (20, 'Approve', 'select hr.decide_leave(:P7_ID::int, ''APPROVED'', :P7_DECISION_NOTE)', 'APPROVE', 'Leave approved.'),
  (30, 'Reject', 'select hr.decide_leave(:P7_ID::int, ''REJECTED'', :P7_DECISION_NOTE)', 'REJECT', 'Leave rejected.'),
  (40, 'Withdraw', 'select hr.withdraw_leave(:P7_ID::int)', 'WITHDRAW', 'Request withdrawn.')
) x(seq, name, code, btn, msg)
 where a.alias = 'hr' and p.page_no = 7;

insert into meta.dynamic_action (page_id, seq, name, event, trigger_element, condition_type, action,
                                 affected_items, code, items_to_submit)
select p.id, 10, 'Count working days', 'change', 'P7_START_DATE,P7_END_DATE', 'is_not_null', 'set_value',
       'P7_DAYS', 'select hr.business_days(:P7_START_DATE::date, :P7_END_DATE::date)', 'P7_START_DATE,P7_END_DATE'
  from meta.page p join meta.app a on a.id = p.app_id where a.alias = 'hr' and p.page_no = 7;

-- Page 9: audit trail (ADMIN; also protected by RLS) ------------------------
insert into meta.page (app_id, page_no, name, title, parent_page, authz)
select id, 9, 'Audit trail', 'Audit trail', 1, 'ADMIN' from meta.app where alias = 'hr';

insert into meta.region (page_id, seq, title, type, source, config)
select p.id, 10, 'Changes recorded by the hr.audit() trigger', 'report',
       E'select changed_at, changed_by, table_name, row_pk as "key", action, old_values, new_values\n  from hr.audit_log\n order by id desc',
       '{"page_size": 20}'
  from meta.page p join meta.app a on a.id = p.app_id where a.alias = 'hr' and p.page_no = 9;

-- Navigation menu ------------------------------------------------------------
with a as (select id from meta.app where alias = 'hr')
insert into meta.nav_entry (app_id, seq, label, icon, target_page, authz)
select a.id, x.seq, x.label, x.icon, x.page, x.auth from a, (values
  (1, 'Dashboard', 'home', 1, null),
  (30, 'Leave requests', 'calendar', 6, null),
  (90, 'Administration', 'shield', null, 'ADMIN')
) x(seq, label, icon, page, auth);

with a as (select id from meta.app where alias = 'hr')
insert into meta.nav_entry (app_id, parent_id, seq, label, icon, target_page, authz)
select a.id, (select n.id from meta.nav_entry n where n.app_id = a.id and n.label = x.parent), x.seq, x.label, x.icon, x.page, x.auth
  from a, (values
  ('Employees', 10, 'Employee list', 'list', 2, null),
  ('Employees', 20, 'Org chart', 'org', 8, null),
  ('Administration', 10, 'Audit trail', 'history', 9, 'ADMIN')
) x(parent, seq, label, icon, page, auth);

-- "Employees" becomes a parent entry; its children point to pages 2 and 8
update meta.nav_entry n set target_page = null, seq = 10
  from meta.app a where a.id = n.app_id and a.alias = 'hr' and n.label = 'Employees' and n.parent_id is null;
update meta.nav_entry n set seq = 20
  from meta.app a where a.id = n.app_id and a.alias = 'hr' and n.label = 'Departments';
