-- =====================================================================
-- Tutorial app: "Tasks" (see docs/guide/10-tutorial.md)
--
-- A personal task list where every user sees only their own tasks, built
-- entirely in SQL. Run it with:
--   psql "$DATABASE_URL" -f examples/tasks-app.sql
-- then open http://127.0.0.1:3100/a/tasks and sign in as ann / ann-password
-- (or bob / bob-password).
-- =====================================================================

begin;

-- 1. Schema, table and business logic ------------------------------------
create schema tasks;

create table tasks.task (
  id         int generated always as identity primary key,
  owner      text not null default meta.app_user(),   -- the signed-in app user
  title      text not null,
  priority   text not null default 'NORMAL' check (priority in ('LOW', 'NORMAL', 'HIGH')),
  due_date   date,
  done       boolean not null default false,
  done_at    timestamptz,
  created_at timestamptz not null default now()
);

-- Business rule in PL/pgSQL, called from a button.
create function tasks.complete(p_id int) returns void
language plpgsql as $$
begin
  update tasks.task set done = true, done_at = now()
   where id = p_id and not done;
  if not found then
    raise exception 'This task is already done (or it is not yours).';
  end if;
end
$$;

-- 2. The app's database role ("parsing schema") and row level security ---
create role app_tasks nologin;
grant app_tasks to pgkiln_runtime;
grant usage on schema tasks to app_tasks;
grant select, insert, update, delete on tasks.task to app_tasks;
grant execute on all functions in schema tasks to app_tasks;

alter table tasks.task enable row level security;
create policy own_tasks on tasks.task
  using (owner = meta.app_user())
  with check (owner = meta.app_user());

-- 3. The application --------------------------------------------------------
insert into meta.app (alias, name, home_page, authentication, db_role)
values ('tasks', 'Tasks', 1, 'app_users', 'app_tasks');

insert into meta.app_user (app_id, username, password_hash, roles)
select id, u.name, meta.hash_password(u.pw), '{}'
  from meta.app, (values ('ann', 'ann-password'), ('bob', 'bob-password')) u(name, pw)
 where alias = 'tasks';

-- Report page 1 + modal form page 2, generated by the wizard.
select meta.generate_crud('tasks', 'tasks.task', 1, 2, 'My tasks', 'check');

-- Show fewer columns in the report, open tasks first.
update meta.region r
   set source = E'select id, title, priority, due_date, done\n  from tasks.task\n order by done, due_date nulls last, id',
       config = r.config || '{"headings": {"id": "#"}}'
  from meta.page p join meta.app a on a.id = p.app_id
 where r.page_id = p.id and a.alias = 'tasks' and p.page_no = 1;

-- The form: owner and timestamps are managed by the database, not the user.
delete from meta.item i using meta.page p, meta.app a
 where i.page_id = p.id and p.app_id = a.id and a.alias = 'tasks' and p.page_no = 2
   and i.name in ('P2_OWNER', 'P2_DONE_AT', 'P2_CREATED_AT', 'P2_DONE');

update meta.item i set type = 'radio', lov = 'STATIC:Low;LOW,Normal;NORMAL,High;HIGH', default_value = 'NORMAL'
  from meta.page p join meta.app a on a.id = p.app_id
 where i.page_id = p.id and a.alias = 'tasks' and p.page_no = 2 and i.name = 'P2_PRIORITY';

-- A "Mark done" button that calls the PL/pgSQL function ...
insert into meta.button (page_id, region_id, seq, name, label, action, target_page, condition)
select p.id, r.id, 25, 'COMPLETE', 'Mark done', 'submit', 1,
       ':P2_ID is not null and not exists (select 1 from tasks.task where id = :P2_ID::int and done)'
  from meta.page p join meta.app a on a.id = p.app_id join meta.region r on r.page_id = p.id
 where a.alias = 'tasks' and p.page_no = 2;

insert into meta.process (page_id, seq, name, type, code, when_button, success_message)
select p.id, 20, 'Complete task', 'sql', 'select tasks.complete(:P2_ID::int)', 'COMPLETE', 'Nice work!'
  from meta.page p join meta.app a on a.id = p.app_id
 where a.alias = 'tasks' and p.page_no = 2;

-- ... a validation ...
insert into meta.validation (page_id, seq, name, item_name, type, expression, message)
select p.id, 10, 'Due date not in the past', 'P2_DUE_DATE', 'sql',
       ':P2_DUE_DATE is null or :P2_DUE_DATE::date >= current_date or :P2_ID is not null',
       'The due date cannot be in the past.'
  from meta.page p join meta.app a on a.id = p.app_id
 where a.alias = 'tasks' and p.page_no = 2;

-- ... and a dynamic action: high priority tasks suggest a due date of tomorrow.
insert into meta.dynamic_action (page_id, seq, name, event, trigger_element, condition_type, condition_value,
                                 action, affected_items, code, items_to_submit)
select p.id, 10, 'Suggest due date for high priority', 'change', 'P2_PRIORITY', 'equals', 'HIGH',
       'set_value', 'P2_DUE_DATE', 'select coalesce(:P2_DUE_DATE::date, current_date + 1)', 'P2_DUE_DATE'
  from meta.page p join meta.app a on a.id = p.app_id
 where a.alias = 'tasks' and p.page_no = 2;

-- 4. A dashboard region on the report page ---------------------------------
insert into meta.region (page_id, seq, title, type, columns, template, source, config)
select p.id, 5, 'Overview', 'cards', 12, 'plain',
       E'select ''Open'' as title, count(*) filter (where not done)::text as badge, ''list'' as icon from tasks.task\nunion all\nselect ''Overdue'', count(*) filter (where not done and due_date < current_date)::text, ''calendar'' from tasks.task\nunion all\nselect ''Done'', count(*) filter (where done)::text, ''check'' from tasks.task',
       '{"style": "metric"}'
  from meta.page p join meta.app a on a.id = p.app_id
 where a.alias = 'tasks' and p.page_no = 1;

commit;
